{10}{}{Guardar.}
{20}{}{Eles todos tribais parecem os mesmos...}
{100}{}{Ei! Você! Homem sujo! O que você está fazendo aqui?! Esta vila é altamente secreta e ninguém do mundo exterior pode entrar na nossa terra sagrada!}
{200}{}{Eu sou apenas um viajante de Klamath.}
{250}{}{Saia daqui! Pessoas como você vem aqui só pra roubar tudo e criar problemas. É por isso que nós não gostamos de turistas!}
{300}{}{Você tem frasco de cerveja?}
{350}{}{O que é cerve? Eu nunca ouvi sobre tal coisa... Talvez nosso xamâ louco terá uma, ele tem muitas misturas e poções estranhas.}
{400}{}{Eu procuro algo pra beber... E o que você faz?}
{450}{}{Nossa bruxa põe outro aldeão no templo das provações e eu devo observá-lo. Ninguém já retornou de lá. Nós precisamos de bravo campeão pra fazer missão perigosa a qual nos salvará nestes tempos sombrios.}
{910}{}{FIM }
{920}{}{VOLTAR }
