{10}{}{Escolhido.}
{20}{}{Eles todos tribais parecem os mesmos...}
{100}{}{Maldição! Eu morrerei aqui... Eu sei disso!}
{200}{}{Oi cara! O que é que há?}
{250}{}{A bruxa me escolheu para o teste no templo. Eu thenho medo de entar porque ninguém volta... você consegue ouvir esse grito na escuridão? Todo mundo morre lá. Ela deve ser realmente estúpida para mandar nossos irmãos e irmãs nesse teste idiota só para morrer!}
{300}{}{Você tem cerveja?}
{350}{}{[Ele olha pra escuridão do templo e ignra sua pergunta]}
{400}{}{Estou tão sedento! Talvez eu acharei alguma cerveja neste... tamplo?}
{450}{}{Oh sim... templo contém muitos tesouros do mundo antigo. Agora me deixe em paz! Eu devo ter feito primeiro pequeno passo na escuridão... Mas eu temo mover minha perna.}
{910}{}{FIM }
{920}{}{VOLTAR }
