{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Oi estranho.. Você ouve essa voz estranha do poço?}
{200}{}{Sim... soa como grito de cachorro.}
{250}{}{Não, eu acho que é algo diferente. Deve ser um antigo fantasma da terra... e ele necessita de sacrifícios feitos de elemento terra. Vá para a plantação de milho e me traga uma pedra grande.}
{300}{}{Olha! Eu achei um.}
{350}{}{Aqui está o sacrifício para os deuses da terra! [Aldeão joga a pedra dentro do poço e depois de um breve grito permanece um silêncio eterno.] Obrigado meu amigo, agora o fantasma da terra está feliz e não grita mais. Aqui está sua recompensa, uma flor belíssima que cresceu perto do poço.}
{400}{}{Nós somos agora abençoados pela terra!}
{401}{}{Tantas moscas ao redor do poço mágico!}
{402}{}{Silêncio abençoado.}
{403}{}{Uh... O que é esse cheiro?}
{404}{}{Obrigado meu amigo!}
{910}{}{FIM }
{920}{}{VOLTAR }
