{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Estou tão cansado... Ei homem sujo! Você pode me ajudar?}
{200}{}{Uh, não tenho certeza... O que você precisa?}
{250}{}{Xamã quer entregar mais coisas de merda para ele, mas minha pá é muito pesada. Traga uma nova, uma limpa. Ela deve estar em algum lugar perto daquelas barracas! [Ela aponta o dedo em uma direção aleatória e senta no chão tentando limpar os sapatos]}
{300}{}{Eu achei pá limpa!}
{350}{}{Obrigado cara... Eu vou terminar meu trabalho mais tarde, porque eu estou muito cansado. Pegue essas coisas brilhantes que Vic me deu em troca de um beijo. Eu ouvi por aí que muitas coisas podem ser compradas com aquela coisa chamada... "dinheiro".}
{400}{}{Estou tão cansado...}
{401}{}{Eu cheiro mal igual brahmin...}
{402}{}{Maldição! Eu tenho sapatos pesados...}
{403}{}{Outro dia maravilhoso...}
{404}{}{Me deixe em paz, estou ocupado...}
{910}{}{FIM }
{920}{}{VOLTAR }
