{100}{}{Você tem uma visão incrível mas você se sente enjoado.}
{101}{}{Eu sou o senhor mosca! E eu sou tão rápido quanto o vento!}
{102}{}{Onde estão os meus sapatos? Polícia! Alguém roubou os meus sapatos!!}
{103}{}{Uau... Minha cabeça é tão GRANDE!}
{104}{}{Eu achei ouro! hahah! ...Não é só uma pedra.}
{105}{}{Olha esse arco-íris!!}
{106}{}{Eu não consigo mexer a minha perna! Ai! Socorro!}
{107}{}{O que tem de errado com os meu dedos? Eu tenho muitos deles...}
{108}{}{Eu sou unvisible!}
{109}{}{Eu sou mais rápido que uma bala! Uau eu me mexo muito rápido!}
{110}{}{Cadê a minha... Porra?! Uh... Está na minha mão...}
{111}{}{O quê é aquilo no céu?... É um Alien!?...}
{112}{}{Arrgh! Rato cobra comeu meus sapatos!}
{113}{}{Eu sou tão grande! Eu poderia te esmagar só com o meu dedo!}
{114}{}{Porque minhas calças estão de repente tão molhadas?!}
{115}{}{Ei! Você! Cabeça de pássaro! Tenha dó!}
{116}{}{Eu acho que eu poderia pular sobre a casa...}
{117}{}{Eu sou um coelho... Eu quero pular em cima de uma árvore!}
{118}{}{Um rato?! Eu tenho um rato no bolso!}
{119}{}{Porque essas pedras estão me observando?!}
{120}{}{Eu perdi meu chapéu!! Ah... eu tinha um chapéu antes?}
{121}{}{Onde estão meus cabelos?! Uh... eles estão no meu bolso!}
{122}{}{Droga! Meu Schlanger está vazio!}
{123}{}{Tudo está tão lento... Ei você! Venha aqui!}
{124}{}{Sim eu gosto daquela música!}
{125}{}{O quê você quer de mim?! Sai da frente ratasana de merda!}
{126}{}{O quê essas moscas querem de mim?}
{127}{}{O quê esse cachorro disse?}
{128}{}{UaU! Minha mão é tão longa!!}
{129}{}{Porque eu estou tão verde?! Oh não eu sou um supermutante!!}
{130}{}{Polícia! O coelho roubou meus dedos!!}
