{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Finalmente! Depois de todos esses anos eu teriminei... eu terminei esse monumento}
{200}{}{Como você fez?}
{250}{}{Nossos anciãos não nos permitem usar coisas técnicas. Com a britadeira que Vic me deu eu consegui fazer em alguns dias, mas eu costumava usar uma ferramenta tradicional: garfo de madeira. Eu gastei metade da minha vida para fazê-la, mas como vê com o resultado, valeu a pena.}
{300}{}{O quê é aquela cara?}
{350}{}{Sou eu! Você não vê isso? Uh talvez você não vê isso... porque eu estou velho agora, mas sou eu. É o meu rosto quando eu tinha 40 anos.}
{400}{}{Porquê você a fez?}
{450}{}{Porquê?! Que pergunta idiota? Porque eu poderia ser a pessoa mais popular da vila inteira. Só imagina meu rosto gigantesco esculpido no meio da vila! Infelizmente só nossa xamã entende minha ideia sobre o monumeto.}
{910}{}{FIM }
{920}{}{VOLTAR }
