{10}{}{Witch. }
{20}{}{Very old woman, probably leader of this small community..}
{100}{}{News run quickly across this small village. I heard that you survived temple of trials, is that true? Let me tell you something.. champion. We have  many problems here and i believe that everyone can be fix just like that in one minute using holy artefact called holy GECK. You must find that item! It is said that such item will bring happiness and life to the wasteland!}
{200}{}{Uh.. but why me?}
{250}{}{Because its your destiny! You come here to our village not by mistake.. prophecy say many things about you champion. Anyway, Vic trader told me about GECK and i want it! So go now on wasteland and bring me one or two. Uh.. and talk with Vic first, he known much more about that item. }
{300}{}{It was really hard but somehow i found it!}
{350}{}{Incredible you are truly champion! [she open quickly bag and found something.. very strange inside and she give it to you] Do you known how use this GECK? Please find out how its work! Our destiny is in your hands brave one! }
{400}{}{Do you known how its work?}
{401}{}{You made big quest.. but many new adventures waiting for you!}
{402}{}{Finally i have GECK.. am so happy! But how it work?}
{403}{}{Please find how work this holy artefact!}
{404}{}{This item will bring life and happines to the wasteland!}
{910}{}{FIM }
{920}{}{VOLTAR }
