{10}{}{Gecko Engineer. }
{20}{}{He look mutated.. like everyone who work in Gecko Plant..}
{100}{}{[He sleep on chair] Zzzzzzz...}
{200}{}{Damn! I remember that face! You sell me radioactive beer, which make big hole in my brain! I lost my memories ashole!}
{250}{}{[He wake up and look scarry at you] Look.. am sorry.. take these keys which i found on floor.. and please dont be agressive..}
{300}{}{Uh.. ok, what you do here in Klamath anyway?}
{350}{}{Am on one month vacation, now let me continue my dreams.. [and he fall into long deep sleep, this job in Gecko must be really hard]}
{400}{}{Zzzzzz...}
{401}{}{::SNIFF::}
{402}{}{..Frank! throw me screw number eight!..}
{403}{}{..Such a dumb ashole! I tell you to close pipe!..}
{404}{}{..I think we got radioactive lake again!..}
{910}{}{[Let him sleep] }
{920}{}{VOLTAR }
