{100}{}{Você tem uma visão incrível mas você se sente enjoado.}
{101}{}{Am BATMAN! And i have very cool car!  }
{102}{}{Am Superman strongh like horse!  }
{103}{}{Argggh! Am SUPER mutant! }
{104}{}{Am Bond.. JAMES Bond! }
{105}{}{Hahahah! Am Spiderman! }
{106}{}{Am Turtle Ninja! Master of karate! }
{107}{}{Am Chuck Norris! I will kick your face! }
{108}{}{Arrgghh Am HULK! }
{109}{}{Am Richard Wintage from TV! }
{110}{}{Am Harrison! Master of modifications! }
{111}{}{Am magapornstar yeah!  }
{112}{}{Who are me!? Am Unvisible!  }
{113}{}{Am Pipboy3000 and i have HEROIC charisma! }
{114}{}{Am MISTER FLY! Hahahah! }
{115}{}{Am forum administrator! }
{116}{}{Am Gorgeous Nurse yeesss..}
{117}{}{Am Hobbit! And i have RING! }
{118}{}{Hahahhh! am RICH!  }
{119}{}{GOLD! I can turn rocks to gold! }
{120}{}{Am VIC supertrader!  }
{121}{}{Hahah! I dont known who am i ..but not ME!  }
{122}{}{Am Veeery BIG tree!  }
{123}{}{Am dog shit! SOMETHING WRONG!  }
{124}{}{Am brahmin shit! Whats wrong!  }
{125}{}{Am dirty RAT! What the fuck! }
{126}{}{Am president! And i have A-Bomb! }
{127}{}{Am tricky kid and am VERY quick! }
{128}{}{Please HELP me i lost my head! }
{129}{}{Am SNAKE i escaped from New York!  }
{130}{}{WHY AM SO TIRED!? }
