{10}{}{Vakt.}
{20}{}{De allihop stammedlemmar ser likadana ut..}
{100}{}{Hörru du! Smutsgubbe! Vad gör du här?! Den här byn är topphemlig och ingen från världen utanför får komma in i vårt heliga land!}
{200}{}{Är bara resenär från Klamath.}
{250}{}{Get out of here! Peoples like you come here only to steal everything and make troubles. Thats why we dont like tourists!  }
{300}{}{Do you have flask of beer? }
{350}{}{What is beee? I never heard about such thing.. Maybe our crazy shaman will have one, he got many strange mixtures and potions.}
{400}{}{I search something to drink.. And what you do?}
{450}{}{Our witch put another villager to temple of trails and i must watch him. Already nobody returned from there. We need brave champion to made dangerous quest which will save us in these dark times.}
{910}{}{END }
{920}{}{BACK }
