{10}{}{Den utvalda.}
{20}{}{De allihop stammedlemmar ser likadana ut..}
{100}{}{Fan! Jag kommer att dö där... jag visste det!}
{200}{}{Hej, mannen! Hur är läget?}
{250}{}{Witch chosen me for test in temple. I fear to enter because nobody return.. can you hear this scream from darkness? Everyone died there. She must be really stupid to kill our brothers and sisters in this dumb test!}
{300}{}{Do you have beer?}
{350}{}{[He look into temple darkness and ignore your question]}
{400}{}{Am so thirsty! Maybe i will find some beer it this.. tample?}
{450}{}{Oh yes.. temple contain many treasures from ancient world. Now leave me alone! I must made first little step into darkness.. but i fear to move my leg.}
{910}{}{SLUT}
{920}{}{TILLBAKA}
