{10}{}{Villager. }
{20}{}{They everyone look the same..}
{100}{}{I lost my dog. Uh.. and i fear that someone eat him! Outsider, can you investigate where go my dirty animal? His name was "Klint".}
{200}{}{I dont like to solve riddles.}
{250}{}{Uh yes.. you dont look very clever. Nevermind, i will just wait here until he return. Probably he run around village and hunt for rats.}
{300}{}{Do you have beer?}
{350}{}{[He look around searching dog and ignore your question]}
{400}{}{Tell me about this village.}
{450}{}{We live in peace far from civilization. Elders say that technic bring only pain and devastation so we must believe only in traditional shamans magic. But one day come to us trader Vic with his amazing stuff. Holy ghosts abandon us and many peoples get sick. }
{910}{}{SLUT}
{920}{}{TILLBAKA}
