{100}{}{You have wonderfull vision but you feel sick. }
{101}{}{Am mister fly! And am quick like wind!  }
{102}{}{Where is my shoes? Police! Someone steal my shoes!!  }
{103}{}{Wow.. my head is so BIG!  }
{104}{}{I found gold! hahah! ..no its stone. }
{105}{}{Look at this rainbow!! }
{106}{}{I cant move my leg! Argh!! Help me! }
{107}{}{Whats wrong with my fingers? I have them too much.. }
{108}{}{Am unvisible! }
{109}{}{Am faster than bullet! Wow i move so fast! }
{110}{}{Where is my schlager?! Uh.. i got it in hand.. }
{111}{}{What is that on sky? ..its UFO!?  }
{112}{}{Arrgh! Snake rat eat my shoes!  }
{113}{}{Am so big! I could crush you by my finger! }
{114}{}{Why my pants are suddenly so wet?! }
{115}{}{Hey! You! Birdhead! Come on! }
{116}{}{I think i could jump over house.. }
{117}{}{Am rabbit.. I want to climb on tree! }
{118}{}{Mouse?! I have mouse in pocket!  }
{119}{}{Why these rocks watch at me?! }
{120}{}{I lost my hat!! Uh.. do i have hat before?  }
{121}{}{Where is my hairs?! Uh.. i got them in pocket!  }
{122}{}{Damn! My Schlager is empty!  }
{123}{}{Everything so slowly.. Hey you! Come on!  }
{124}{}{Yeah i like that music!!!  }
{125}{}{What you want from me?! Fuck off damn rat! }
{126}{}{What these flies want from me?! }
{127}{}{What this dog say?! }
{128}{}{WoW! My hand is so long!! }
{129}{}{Why am so green?! Oh no am supermutant!!  }
{130}{}{Police! Rabbit steal my fingers!! }
