{10}{}{Sue. }
{20}{}{She seem to be one from your seven childrens..}
{100}{}{Agh! These bastards dont want play RPG with me because i dont known rules! Where you was trough these whole days anyway?! Did you found some food?}
{200}{}{I have very important quest to do.}
{250}{}{Uh.. ok! I fear to go outside town. Monica say she seen very BIG rat and she run again somewhere. I feel so alone and SAD!}
{300}{}{Sorry kid but i dont remember you..}
{350}{}{Momy say that you got problems with brain! And she search doctor which will make you sometihing bad! Better escape from here, am warning you!}
{400}{}{What is RPG?}
{450}{}{Its strange game, they play it many days. I wish i could understand what they talking about and what are these.. rules!}
{910}{}{SLUT}
{920}{}{TILLBAKA}
