{10}{}{Citizen. }
{20}{}{They everyone look the same..}
{100}{}{So you return from your.. journey. Its good to see you again. Uh your wife was very angry and she asked me about sleep with her.. But dont fear she is so ugly that.. Uh i mean.. nothing.}
{200}{}{I dont remember many things from my life.}
{250}{}{Dont you remember when we was farmers trough many years and finally we settle in Klamath? Old good days.. they will never return. Dont worry your problems is probably because radiation and dirty water. Everybody around have problems with health.. even me.}
{300}{}{Can you borrow me some money?}
{350}{}{No i cant. I borrow you them so many times and you olways forgott about that. I dont want to make any deals with you. I heard that miners from Redding found new golden veins, maybe try your luck there.}
{400}{}{Damn! Am so thirsty. I need beer!}
{450}{}{Sadly i dont have any drink. Few days ago i found nuka cola. But i fear to drink and Vic buy it from me for 1 coin. I heard these Nuka-Cola was invented  by mutants! }
{910}{}{SLUT}
{920}{}{TILLBAKA}
