{10}{}{Citizen. }
{20}{}{They everyone look the same..}
{100}{}{Month ago my man go search golden geckos in poison cave. Ofcourse he died there because it was too dangerous and nodoby want to help him. Now am alone and.. are you interested to be my new.. entertainment?}
{200}{}{Uh i dont known.. probably.}
{250}{}{I will give you ten coins for one night!}
{300}{}{Ok am ready..}
{350}{}{Yeah! [She was very brutal and floor was full of broken glass. Trough one night you take more wounds that trough whole travell from Klamath to Arroyo and back.]}
{400}{}{Yeah.. you are WILD!}
{401}{}{I feel better now!}
{402}{}{We must try again later, please dont leave town darling..}
{403}{}{Darling you are so sweet..}
{404}{}{This was HOT! action..}
{910}{}{SLUT}
{920}{}{TILLBAKA}
