{10}{}{Sylvia Moon. }
{20}{}{She is owner and guard of fame Bathhouse.}
{50}{}{ aaa }
{51}{}{ bbb }
{52}{}{ ccc }
{53}{}{ ddd }
{54}{}{ eee }
{100}{}{Welcome to Bathhouse. We have three pornstars, each worth 30$ for half hour. Visit them in her rooms then select your favourite and come back to pay me. I will let you to spend with woman of your dream wonderfull time.}
{200}{}{I want sleep with Isabell Sweet. }
{250}{}{Thank you darling. Isabell Sweet is now ready for you, go to her room.. [She take from you 30 coins and very sensitive point finger on corridor]}
{260}{}{Sorry but you dont have enough money. Come back later. }
{300}{}{Paulina Hot is woman of my dreams.}
{350}{}{Thank you darling. Paulina Hot is now ready for you, go to her room.. [She take from you 30 coins and very sensitive point finger on corridor]}
{360}{}{Sorry but you dont have enough money. Come back later. }
{400}{}{Give me night with Samantha Wet.}
{450}{}{Thank you darling. Samantha Wet is now ready for you, go to her room.. [She take from you 30 coins and very sensitive point finger on corridor]}
{460}{}{Sorry but you dont have enough money. Come back later. }
{500}{}{Why you carry this shotgun?}
{550}{}{Our girls are really good, almost that good as pornstars from New Reno. Someone could try to capture them and sell later to slavery guild. So i keep them as treasure. Anyway they dont want to work when dont feel safety enough.}
{600}{}{I want to be movie pornstar!}
{650}{}{We dont make movies here, you must visit New Reno "Porn Club". Ofcourse they will dont hire you as "actor" if your "experience" is lower than 10. Already your SEX-EXP is: }
{700}{}{ pyt6 }
{910}{}{SLUT}
{920}{}{TILLBAKA}
