{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Oi estranho.. Você ouve essa voz estranha do poço?}
{200}{}{Sim... soa como grito de cachorro.}
{250}{}{No i think its something different. It must be ancient ghost of earth..  and he need sacrifice made from earth element. Go on corn filed and bring me some big stone..}
{300}{}{Olha! Eu achei um.}
{350}{}{Here is sacrifice for goddes of earth! [Villager throw that stone into well and after short scream remain ethernal silence.] Thank you my friend, now ghost of earth is happy and dont scream anymore. Here is your revard, wonderfull flower which grown near well.}
{400}{}{Nós somos agora abençoados pela terra!}
{401}{}{Tantas moscas ao redor do poço mágico!}
{402}{}{Silêncio abençoado.}
{403}{}{Uh... O que é esse cheiro?}
{404}{}{Obrigado meu amigo!}
{910}{}{FIM }
{920}{}{VOLTAR }
