{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Eu perdi meu cachorro. Uh... e eu temo que alguém comeu ele! Estranho, você poderia investigar para onde foi o sujo do meu animal? O nome dele era "Klint".}
{200}{}{Eu não gosto de resolver enigmas.}
{250}{}{Uh sim... Você não parece muito esperto. Deixa pra lá, eu apenas esperarei aqui até ele retornar. Provavelmente ele correr pela vila e caçar ratos.}
{300}{}{Você tem cerveja?}
{350}{}{[Ele olha ao redor procurando cachorro e ignora sua pergunta]}
{400}{}{Me fale sobre esta vila.}
{450}{}{Nós vivemos em paz longe da civilização. Os anciãos dizem que técnicas trazem apenas dor e devastação, então nós devemos acreditar apenas em tradicionais mágicas shamans. Mas um dia Vic o comerciante veio até nós com coisas maravilhosas. Os grandes fantasmas nos abandoram e muitas pessoas ficaram doentes.}
{910}{}{FIM }
{920}{}{VOLTAR }
