{100}{}{Você tem uma visão incrível mas você se sente enjoado.}
{101}{}{Eu sou o senhor mosca! E eu sou tão rápido quanto o vento!}
{102}{}{Onde estão os meus sapatos? Polícia! Alguém roubou os meus sapatos!!}
{103}{}{Uau... Minha cabeça é tão GRANDE!}
{104}{}{Eu achei ouro! hahah! ...Não é só uma pedra.}
{105}{}{Olha esse arco-íris!!}
{106}{}{Eu não consigo mexer a minha perna! Ai! Socorro!}
{107}{}{O que tem de errado com os meu dedos? Eu tenho muitos deles...}
{108}{}{Am unvisible! }
{109}{}{Eu sou mais rápido que uma bala! Uau eu me mexo muito rápido!}
{110}{}{Cadê a minha... Porra?! Uh... Está na minha mão...}
{111}{}{O quê é aquilo no céu?... É um Alien!?...}
{112}{}{Arrgh! Rato cobra comeu meus sapatos!}
{113}{}{Eu sou tão grande! Eu poderia te esmagar só com o meu dedo!}
{114}{}{Porque minhas calças estão de repente tão molhadas?!}
{115}{}{Ei! Você! Cabeça de pássaro! Tenha dó!}
{116}{}{Eu acho que eu poderia pular sobre a casa...}
{117}{}{Eu sou um coelho... Eu quero pular em cima de uma árvore!}
{118}{}{Um rato?! Eu tenho um rato no bolso!}
{119}{}{Porque essas pedras estão me observando?!}
{120}{}{I lost my hat!! Uh.. do i have hat before?  }
{121}{}{Where is my hairs?! Uh.. i got them in pocket!  }
{122}{}{Damn! My Schlager is empty!  }
{123}{}{Everything so slowly.. Hey you! Come on!  }
{124}{}{Yeah i like that music!!!  }
{125}{}{What you want from me?! Fuck off damn rat! }
{126}{}{What these flies want from me?! }
{127}{}{What this dog say?! }
{128}{}{WoW! My hand is so long!! }
{129}{}{Why am so green?! Oh no am supermutant!!  }
{130}{}{Police! Rabbit steal my fingers!! }
