{10}{}{New bartender. }
{20}{}{Crazy folk..}
{100}{}{Yes! hahah! I have record! YEAH!}
{200}{}{What you do?}
{250}{}{Am playing Giana Sister.. JUMP YOU BITCH! ..damn! ..YEAH! [he point on some pixels on monitor and say] Look i olways get problems to get these diamonds, i think it must be unvisible platform to jump for this bonus..}
{300}{}{What is that.. machine?}
{350}{}{C64, old comp but so many cool games! Yes i should use it to count stock and payments but i found its entertainment possibilities and now i cant stop!}
{400}{}{Are you bartender? I want beer!}
{450}{}{Yeah! Wonderfull job! Sory we will talk later! [you see only flashing pixels on monitor monitor, but he seem to be very busy on them] NOW! ..hahah BONUS! ..run ..RUN ..RUN!! ..YEAH NEXT LEVEL!!}
{500}{}{BOM! }
{501}{}{SWING! }
{502}{}{ZIP! }
{503}{}{WIZ! }
{504}{}{JAB! }
{505}{}{PING! }
{506}{}{UUU! }
{507}{}{ZAP! }
{508}{}{HOP! }
{509}{}{BAAM! }
{910}{}{FIM }
{920}{}{VOLTAR }
