{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{I lost my dog. Uh.. and i fear that someone eat him! Outsider, can you investigate where go my dirty animal? His name was "Klint".}
{200}{}{Eu não gosto de resolver enigmas.}
{250}{}{Uh sim... Você não parece muito esperto. Deixa pra lá, eu apenas esperarei aqui até ele retornar. Provavelmente ele correr pela vila e caçar ratos.}
{300}{}{Você tem cerveja?}
{350}{}{[Ele olha ao redor procurando cachorro e ignora sua pergunta]}
{400}{}{Me fale sobre esta vila.}
{450}{}{We live in peace far from civilization. Elders say that technic bring only pain and devastation so we must believe only in traditional shamans magic. But one day come to us trader Vic with his amazing stuff. Holy ghosts abandon us and many peoples get sick. }
{910}{}{FIM }
{920}{}{VOLTAR }
