{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{I cant believe! You pass trough temple, nobody made it before! You are now our champion!. Go and talk with elder, she have something very important to tell you.}
{200}{}{Uh... Você é este guarda o qual eu vi perto da entrada do templo? Lamento, vocês todos tribais parecem os mesmos pra mim.}
{250}{}{Yes am guard and great warrior "Klint" By the way i hate this bastard who call his dog my fame name. Hopefully i fixed that problem yesterday and i feel better now. }
{300}{}{E o que acontece com o cara que teme entrar?}
{350}{}{Ele escapou através da floresta no lado de fora da vila, do mesmo jeito pelo qual você chegou aqui. Eu espero que ele nunca retorne porque eu não gosto de perdedores!}
{400}{}{Sim sou herói! Agora me dê cerveja!}
{450}{}{Sorry but i dont known what it is.. Talk with Elder, she known many things about holy artefacts. And she deal with trader Vis which bring us many strange stuff from outside world.}
{910}{}{FIM }
{920}{}{VOLTAR }
