{10}{}{Den News. }
{20}{}{Many dirty pages attached to piece of wood..}
{100}{}{=== DEN = NEWS === }
{200}{}{"Hero Jet" ONLY 20$ !!! }
{250}{}{AMAZING Few days ago i invented powerfull drug which help to feel like REAL hero! JUST 20$ come to my house i have them lot in my stock. You can be Batman, Spierman or even Chuck Norris! AMAZING}
{300}{}{I found UFO near Navarro!}
{350}{}{I seen many unidentified obiects over Navarro base and i found few from them crased on desert. Pay me 3000$ and i will sell you that wonderfull vehicle! I have them THREE on my junkyard!}
{400}{}{JOIN TO ARMY TODAY }
{450}{}{We search new recruits to Brotherhood of Steel army. Visit our bunker in Den and talk with sir Marcus from Blood Raven squad. Earn richness and fame during battles against mutants! }
{910}{}{FIM }
{920}{}{VOLTAR }
