{10}{}{Garde.}
{20}{}{Ils se ressemblent tous...}
{100}{}{Hé ! Toi ! Sale type ! Qu'est-ce que tu fais ici ?! Ce village est top secret et personne d'autre ne peut entrer sur notre terre sainte !}
{200}{}{Je suis un simple voyageur de Klamath.}
{250}{}{Sortez d'ici ! Les gens comme vous viennent ici pour tout voler et créer des problèmes. C'est pour ça qu'on n'aime pas les touristes !}
{300}{}{Tu as une flasque de bière ?}
{350}{}{Qu'est-ce que c'est ? Je n'ai jamais entendu parler d'une telle chose... Peut-être que notre chaman fou en aura un, il a beaucoup de mélanges et de potions étranges.}
{400}{}{Je cherche quelque chose à boire... Et qu'est-ce que tu proposes ?}
{450}{}{Notre chman a envoyé un autre villageois au temple des sentiers et je dois le surveiller. Déjà personne n'est revenu de là-bas. Nous avons besoin d'un champion courageux pour faire une quête dangereuse qui nous sauvera en ces temps sombres.}
{910}{}{END }
{920}{}{BACK }
