{10}{}{Chosen One. }
{20}{}{Ils se ressemblent tous...}
{100}{}{Damn! I will die there.. i known that! }
{200}{}{Bonjour ! Quoi de neuf ?}
{250}{}{Une sorcière m'a choisi pour un test dans le temple. J'ai peur d'entrer car personne n'en revient... peux-tu entendre ce cri venant des ténèbres ? Tout le monde est mort là-bas. Elle doit être vraiment stupide pour tuer nos frères et soeurs dans ce test stupide !}
{300}{}{As-tu de la bière ?}
{350}{}{[He look into temple darkness and ignore your question]}
{400}{}{Am so thirsty! Maybe i will find some beer it this.. tample?}
{450}{}{Oh oui... le temple contient de nombreux trésors du monde antique. Maintenant, laissez-moi tranquille ! Je dois faire le premier pas dans l'obscurité... mais j'ai peur de bouger ma jambe.}
{910}{}{END }
{920}{}{BACK }
