{10}{}{Villager. }
{20}{}{They everyone look the same..}
{100}{}{I cant believe! You pass trough temple, nobody made it before! You are now our champion!. Go and talk with elder, she have something very important to tell you.}
{200}{}{Uh.. you are this guard which i seen near temple entrance? Sorry your everyone tribals look the same to me.}
{250}{}{Yes am guard and great warrior "Klint" By the way i hate this bastard who call his dog my fame name. Hopefully i fixed that problem yesterday and i feel better now. }
{300}{}{And whats happend with that guy who fear to enter?}
{350}{}{He escaped trough forest outside village, the same way which you come here. I hope he will never return because i dont like losers!}
{400}{}{Yes am hero! Now give me beer!}
{450}{}{Sorry but i dont known what it is.. Talk with Elder, she known many things about holy artefacts. And she deal with trader Vis which bring us many strange stuff from outside world.}
{910}{}{END }
{920}{}{BACK }
