{10}{}{Shaman. }
{20}{}{He look really crazy..}
{100}{}{Hahahah.. look at these shapes and colours!!}
{200}{}{Uh.. what you talking about?}
{250}{}{Hahahah.. sorry i forgot that you dont see what i see! I invented wonderfull mixture. Its made from brahmin shit and broc flower. Unless i dont have too much flowers. Bring me one and i will help you to see hidden side of amazing world!}
{300}{}{I got flower, can you made this mixture for me?}
{350}{}{Oh yeah! [He take flower from you and piece of shit from barrel. After half hour he gived you wonderfull mixture.]}
{400}{}{Help me! Snake bird attack my shoe!}
{401}{}{Why these rocks escaping from me?!}
{402}{}{Wow i have third hand!!}
{403}{}{What is that?! I cant catch it!!}
{404}{}{Fire! My house is under fire!!}
{910}{}{END }
{920}{}{BACK }
