{10}{}{Clara. }
{20}{}{She seem to be one from your seven childrens..}
{100}{}{Dady am 12 years old and i want cosmetic case!}
{200}{}{I dont care about that.}
{250}{}{Please! Please! please! Bring me some cosmetics am old dont you see that?! Please dady! I will tell you where momy hide all money!}
{300}{}{Here is cosmetics.. but first tell me about money.}
{350}{}{Oh thank you! [She quickly run to other room and after minute returned with some old dirty stockings which contain lot of money.]}
{400}{}{Am beauty like pornstar!}
{401}{}{[she look at mirror]}
{402}{}{Yeah! Am superstar!}
{403}{}{[she use cosmetics]}
{404}{}{Hi Hi Hi}
{910}{}{END }
{920}{}{BACK }
