{100}{}{Tienes una excelente visión pero te sientes enferma.}
{101}{}{¡Soy señor mosca! ¡Y vuelo como el viento!}
{102}{}{¿Dónde están mis zapatos? ¡Policía! ¡¡Alguien robó mis zapatos!!}
{103}{}{¡Wow… mi cabeza es tan GRANDE!}
{104}{}{Encontre oro! jaja! ...no es solo piedra}
{105}{}{Mira este arcoíris!!}
{106}{}{No puedo mover mi pierna! Argh!! ayudame!!}
{107}{}{Whats wrong with my fingers? I have them too much.. }
{108}{}{Soy invisible! }
{109}{}{¡Soy más rapido que una bala! ¡Wow, me muevo muy rápido! }
{110}{}{Where is my schlager?! Uh.. i got it in hand.. }
{111}{}{¿Qué es eso en el cielo? ..es un OVNI!?  }
{112}{}{Arrgh! Snake rat eat my shoes!  }
{113}{}{Am so big! I could crush you by my finger! }
{114}{}{Why my pants are suddenly so wet?! }
{115}{}{Hey! You! Birdhead! Come on! }
{116}{}{I think i could jump over house.. }
{117}{}{Am rabbit.. I want to climb on tree! }
{118}{}{Mouse?! I have mouse in pocket!  }
{119}{}{Why these rocks watch at me?! }
{120}{}{I lost my hat!! Uh.. do i have hat before?  }
{121}{}{Where is my hairs?! Uh.. i got them in pocket!  }
{122}{}{Damn! My Schlager is empty!  }
{123}{}{Everything so slowly.. Hey you! Come on!  }
{124}{}{¡¡¡Si, Me gusta esa música!!!  }
{125}{}{What you want from me?! Fuck off damn rat! }
{126}{}{What these flies want from me?! }
{127}{}{What this dog say?! }
{128}{}{WoW! My hand is so long!! }
{129}{}{Why am so green?! Oh no am supermutant!!  }
{130}{}{Police! Rabbit steal my fingers!! }
