{10}{}{Nice Female. }
{20}{}{She look much better from other females in this village and it seem like she used cosmetic case lately.}
{100}{}{Helo outsider, can you help me? [She watch at you in hope and from inside of tent you hear someone voices in pain]}
{200}{}{Sure, why not..}
{250}{}{Few days ago i buy cosmetic case from Vic to become more attractive, but its not work. So i gived my man mixture from shaman. He got visions that am beaucty and almost asked me about marry. But sadly he is sick now. Bring me xander root i heard that it could neutralise poisons. It should be somewhere on fields..}
{300}{}{Look i have this root!}
{350}{}{[She start to make soup from xander] Thank you, take this cosmetics i dont need them any more, because they not work..}
{400}{}{Am trying to make soup! Leave me alone!}
{401}{}{Why i feel ugly..}
{402}{}{Do you want tasty soup from xander?}
{403}{}{Am not sure this will work but i must try..}
{404}{}{Thank you again!}
{910}{}{FIM }
{920}{}{VOLTAR }
