{10}{}{Klamath News. }
{20}{}{News? They all are old stuff..}
{100}{}{=== K L A M A T H === N E W S === }
{200}{}{[Some picture]}
{250}{}{Its someone photo and writings: This man eat my cat!}
{300}{}{[Wanted!] }
{350}{}{Its some note: "I want Beer! Am so thirsty that i will crazy! Please give me someone just one drink!" uh.. i think i seen it before.. its MY note? }
{400}{}{[HOT STUFF FOR YOU!] }
{450}{}{Its few photos of half-naked womans with big captions: "Bathhouse" There is also dirty note made in hurry which was put here probably by someone other: "Damn! i lost all my money there, but it was worth! And now i will try something better.. powerfull drugs!" }
{910}{}{FIM }
{920}{}{VOLTAR }
