{10}{}{Aldeano.}
{20}{}{Todos aquí tienen el mismo aspecto.}
{100}{}{¡Perdí a mi perro y temo que alguien se lo coma! Forastero, ¿Puedes investigar a dónde fue mi sucio animal? Su nombre era "Klint".}
{200}{}{No me gustan los acertijos.}
{250}{}{Uh, sí… no pareces muy inteligente. No importa, esperaré aquí hasta que regrese. Probablemente corrió por el pueblo cazando ratas.}
{300}{}{¿Tienes algo de cerveza?}
{350}{}{[Mira a su alrededor buscando perro e ignora tu pregunta]}
{400}{}{Háblame de este pueblo.}
{450}{}{We live in peace far from civilization. Elders say that technic bring only pain and devastation so we must believe only in traditional shamans magic. But one day come to us trader Vic with his amazing stuff. Holy ghosts abandon us and many peoples get sick. }
{910}{}{FIN}
{920}{}{REGRESAR}
