{10}{}{Elegida}
{20}{}{You seen him before near entrance to Arroyo temple!}
{100}{}{[He sit in bushes and eat corn]}
{200}{}{What are you doing here?}
{250}{}{Am waiting for night.. i seen incredible things trough window! Am tell you.. i seen everything! EVERY details! It was really HOT action!}
{300}{}{You are from Arroyo.. I seen you before!}
{350}{}{I like that town, and it was good decision to escape from there. Elders say many frighting stories about outside world, but i feel here so great!}
{400}{}{¿Tienes algo de cerveza?}
{450}{}{Do you mean this yellow water in flask which i seen in bar? No i dont have it.. and i dont like any mixtures, i got bad experiences in Arroyo. Shaman promises me wonderfull time but i was sick trough whole day! }
{910}{}{FIN}
{920}{}{REGRESAR}
