{10}{}{Owner of "Golden Gecko"}
{20}{}{He look very sad and nervous..}
{100}{}{Dont you seen caption on doors "out of business"!?}
{200}{}{Why here is so empty.. and you are half naked? }
{250}{}{I lost everything in poker.. i was very close to win house in New Reno, but in last round luck abandoned me. I must think what to do.. Damn! i dont known that nights can be so cold and uncomfortable!}
{300}{}{Do you have beer? }
{350}{}{Its joke? Leave me alone!}
{400}{}{Well.. i dont seen doors!}
{450}{}{Uh i forgot.. i burned every doors because night was cold.}
{910}{}{Ende}
{920}{}{Zurück}
