
{10}{}{Unusual Villager. }
{20}{}{This one look different..}

{100}{}{Helo my friend, its good to see outsider here. Do you have some stuff for barter? I need new battery for radio which Vic sell me lately. By the way are you his friend?}

{200}{}{Why everyone here look the same and you like.. mad max?}
{250}{}{Because am modern villager. Arroyo is separeted into two groups: traditionalists and liberalists. I buy many items from Vic which make me more individualist. And thats make i feel more freedom.. but sadly not so strongh to leave these grounds.}

{300}{}{Am Klamath citizen and i seen Vic few times, but its dont mean that i must be his friend. This man cheat in cards and sell junk.}
{350}{}{No he dont sell junk, but very valuable items! For example this leather armor with one arm and one leg. Or this radio which work entire two minutes! Or this hat with big hole on top. These all are treasures to us villagers, because we live far from civilisation and we never seen before such things!}

{400}{}{Do you have beer flask in your inventory?}
{450}{}{Yes i have beer flask, i mean empty beer flask. Its great item because it make interesting noices when you throw inside small stones and shake it! Vic teach me how do that, its called "instrument".}

{910}{}{ ŒÕ≈÷ }
{920}{}{Õ¿«¿ƒ }

