
{10}{}{Гертруда. }
{20}{}{Вы откуда-то помните эту женщину..}

{100}{}{Просто посмотри на эту картину, и посмотри на себя! Сделай что-нибудь со своим лицом! Где ты был все эти дни? Наши дети голодны, и ты должен починить стены в доме!!}

{200}{}{Мы знакомы?}
{250}{}{Ты настолько пьян, что забыл собственную жену, детей и дом?! Проклятье, я должна как-нибудь рассказать доктору о твоих проблемах с памятью! Всегда одно и тоже, ты куда-то уходишь и не возвращаешься днями, иногда даже месяцами.. зачем я за тебя вышла, засранец?! }

{300}{}{How many.. we got.. childrens?}
{350}{}{Do you really forgot everything or its some kind of dark humor?! We got seven childrens: Mark, Frank, Vitold, Steven, Clara, Sue, Monica.. Now go and bring us some food. I dont know.. hunt for something or buy! No just whole days you search something to drink!!}

{400}{}{But.. do you have some beer? }
{450}{}{WHAT?! Dont tell me anything about alcohol or i kill you! Now do something usefull for our family and fix these walls. Yesterday big rat come to my bed and i dont sleep trough whole night because he dont want to get off from house! I wish you got this rat brain! He is much more smart than you!!}

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

