
{10}{}{Gertruda. }
{20}{}{You remember that woman from somewhere..}

{100}{}{Just look at this picture and look at you! Do something with your face! Anyway where you was trough these whole days? Our childrens are hungry and you must fix home walls someday!!}

{200}{}{Are we meet before?}
{250}{}{Are you drunken so much that you forgot own wife, childrens and house!? Damn i should tell doctor about your memory problems someday! Olways the same, you walk somewhere and not return trough whole days, sometime even months.. why i marry you ashole?! }

{300}{}{How many.. we got.. childrens?}
{350}{}{Do you really forgot everything or its some kind of dark humor?! We got seven childrens: Mark, Frank, Vitold, Steven, Clara, Sue, Monica.. Now go and bring us some food. I dont know.. hunt for something or buy! No just whole days you search something to drink!!}

{400}{}{But.. do you have some beer? }
{450}{}{WHAT?! Dont tell me anything about alcohol or i kill you! Now do something usefull for our family and fix these walls. Yesterday big rat come to my bed and i dont sleep trough whole night because he dont want to get off from house! I wish you got this rat brain! He is much more smart than you!!}

{910}{}{ ŒÕ≈÷ }
{920}{}{Õ¿«¿ƒ }

