
{10}{}{Стивен. }
{20}{}{Похоже, это один из ваших семи детей..}

{100}{}{Система уровней? А сколько их?}
{101}{}{Да, это точно! А что насчет путешествий во времени?}
{102}{}{Например, 10 уровень путешествий во времени будет останавливать время.}
{103}{}{Ну да странно, но игрок может изобрести любой скилл какой хочет, ПОМНИШЬ?}
{104}{}{У меня скилл памяти нулевого уровня, так что я все забыл.}
{105}{}{Да, иногда скилл маленького уровня лучше!}
{106}{}{Чтобы избежать ловушку в сундуке, я использую интуицию, я знаю что может случиться!}
{107}{}{Возраст это тоже скилл! И он считается в процентах. Возраст 100=100%}
{108}{}{Значит когда там 100% или 0% это значит это эффекты ТОЧНО на тебя сработали!}
{109}{}{Да, но алхимик, используя зелье бессмертия, может уменьшит другой скилл: ВОЗРАСТ!}

{110}{}{Я думаю, этот самый лучший: один скилл влияющий на много других скиллов!}
{111}{}{Значит СИТУАЦИЯ это действие когда несколько скиллов влияют друг на друга!}
{112}{}{Да, это так!}
{113}{}{Я иду по коридору и держу факел.}
{114}{}{У вора есть скилл воровать, но у меня есть скилл следить за своим кошельком!}
{115}{}{Ну да.. бывает сложно, но я думаю так лучше всего.}
{116}{}{Сколько раз я мог попытаться совершить какое-то действие, и на каком скилле это основано?}
{117}{}{Дай-ка подумать.. нет, это чушь какая-то..}
{118}{}{Мой любимый - КРАСНЫЙ! }
{119}{}{Я голосую за сотню левелов, и процентов! }

{120}{}{Когда ты рождаешься, твой скилл ВОЗРАСТ равен нулю! }
{121}{}{Хорошо, я держу свой меч сто дней, так что мой скилл ДЕРЖАТЬ равен 100%  }
{122}{}{Скилл ДЕРЖАТЬ влияет на шанс уронить оружие в битве. }
{123}{}{Да! Нам нужно заставить компьютер делать все эти броски!}
{124}{}{Но у нас только одна кость.. она слишком маленькая для бонусов сотого уровня. }
{125}{}{Ты когда-нибудь видет кость d100? Я слышал, они существуют!}
{126}{}{Это обычный лес или болото? Не пытайся меня сново подловить!}
{127}{}{Он не может съесть мой череп, потому что у меня металлическая шляпа, которая выглядит как обычная шляпа!}
{128}{}{Потому что у меня есть скилл кузнеца, и я сделал металлическую шляпу! И никто не видел!}
{129}{}{Потому что это секретный предмет, который не видит даже гейм мастер!}

{130}{}{Quest master and Game master, whats the difference!? }
{131}{}{Hey guys! Ho many days we play here?! I lost time feeling! }
{132}{}{Ok so i thrown dagger.. and what now?}
{133}{}{Everybody should count own throwns..}
{134}{}{But cheating its also skill! So i get bonus to EVERYTHING!}
{135}{}{Luck and cheating are similar, so you gat many bonus.. }
{136}{}{I use my two handed sword which i made from crystal. }
{137}{}{Everything should be possible otherwise we will pluke from boring! }
{138}{}{So you get more experience, its bonus. }
{139}{}{Every living creatures should have WILD element: wild frog, wild horse. }

{140}{}{WILD is skill used by animals and villagers, they live far from towns. }
{141}{}{NOTHING! Do i need to made actions in each second of my life?! }
{142}{}{Well who cares about that, i could try again hundread times! }
{143}{}{Ok so BORING skill will determine how many times you can made action.. }
{144}{}{BORING skill will be based on AGE or experience..}
{145}{}{Because i shoot flame arrows, they have elemental damage! }
{146}{}{Ok so am stand near dragon and am trying to be like stone.. unvisible.}
{147}{}{What skills could have dragons? They are old so have AGE skill 100% }
{148}{}{Age mean bonus to experience, richness, fame, and everything.. }
{149}{}{I have idea lets drawn 100 squares table and throw here stone.. }
{150}{}{And who cares? Its so funny, lets follow it! }

