
{10}{}{Steven. }
{20}{}{He seem to be one from your seven childrens..}

{100}{}{Levels system? but how much them? }
{101}{}{Yes that is correct! And what about timetravelling? }
{102}{}{For example time travelling in level 10 will stop time. }
{103}{}{Yeah its weird but player can invent any skill he want REMEMBER! }
{104}{}{So i got skill memory in level zero so i forgot everything.}
{105}{}{Yes sometime skill in his small level is better!}
{106}{}{To avoid chest trap i could use intuition i konwn whats could happend!}
{107}{}{Age is ALSO skill hehe! And it coud be test by percents. Age 100=100%}
{108}{}{So when you got 100% or 0% it mean that you SURELY get some effects!}
{109}{}{Yeah but alchemic using immortal potion can decrease other skill: AGE!}

{110}{}{I think its best: one skill will affect many other skills!}
{111}{}{So SITUATION mean action where few skills affect one to other!}
{112}{}{Yes thats true!}
{113}{}{Am walking trough corridor and i have torch.}
{114}{}{Thief have his skill to steal but i have skill to watch my money!}
{115}{}{Uh yes.. it could be complicated, but somehow i believe its best way.}
{116}{}{How many times i could try made some action and on how skill its based?}
{117}{}{Let me see.. no it dont make any sense..}
{118}{}{My favourite is RED! }
{119}{}{I vote on hundread levels, percents! }

{120}{}{When you born, your AGE skill is zero! }
{121}{}{Ok so i hold my sword hundread days, so my HOLD skill is 100%  }
{122}{}{HOLD skill is test for chances to drop weapon during battle. }
{123}{}{Yeah! We should have computer to test whole throws all time!}
{124}{}{But when we have one dice.. its too small tor hundread levels bonus.. }
{125}{}{Did you seen ever dice K100? I heard they exist! }
{126}{}{Its normal forest or swamp? Dont try to surprise me again! }
{127}{}{He dont eat my skull because i got metal hat its look like normal hat! }
{128}{}{Because i got smith skill so i made metal hat! And nobody seen that! }
{129}{}{Because its secret item which even game master dont see! }

{130}{}{Quest master and Game master, whats the difference!? }
{131}{}{Hey guys! Ho many days we play here?! I lost time feeling! }
{132}{}{Ok so i thrown dagger.. and what now?}
{133}{}{Everybody should count own throwns..}
{134}{}{But cheating its also skill! So i get bonus to EVERYTHING!}
{135}{}{Luck and cheating are similar, so you gat many bonus.. }
{136}{}{I use my two handed sword which i made from crystal. }
{137}{}{Everything should be possible otherwise we will pluke from boring! }
{138}{}{So you get more experience, its bonus. }
{139}{}{Every living creatures should have WILD element: wild frog, wild horse. }

{140}{}{WILD is skill used by animals and villagers, they live far from towns. }
{141}{}{NOTHING! Do i need to made actions in each second of my life?! }
{142}{}{Well who cares about that, i could try again hundread times! }
{143}{}{Ok so BORING skill will determine how many times you can made action.. }
{144}{}{BORING skill will be based on AGE or experience..}
{145}{}{Because i shoot flame arrows, they have elemental damage! }
{146}{}{Ok so am stand near dragon and am trying to be like stone.. unvisible.}
{147}{}{What skills could have dragons? They are old so have AGE skill 100% }
{148}{}{Age mean bonus to experience, richness, fame, and everything.. }
{149}{}{I have idea lets drawn 100 squares table and throw here stone.. }
{150}{}{And who cares? Its so funny, lets follow it! }

