
{10}{}{Странный народ.}
{20}{}{Он выглядит чокнутым.}

{100}{}{Давай я тебе покажу! [Вы слышите голос человека, спрятавшегося в маленьком переулке, между углом и коробками. Он почти незаметен, так что сначала вам показалось, что это сказала собака, стоящая неподалеку.]}

{200}{}{Uk.. ok shown me.}
{250}{}{Watch! [You see that he dont have any clothes under cloak! But he shown you so quick that you seen almost nothing.]}

{300}{}{What you want from me?!}
{350}{}{I will shown you! Just give me one coin!}

{400}{}{Do you have beer?}
{450}{}{I have something better.. WATCH! [He shown you his dirty body. You lost concentration, and almost fall on ground.] }

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

