
{10}{}{Dog. }
{20}{}{Just some dirty dog..}

{100}{}{Grrrrr... }

{200}{}{What is your name.. AZOR?! }
{250}{}{Woof! }

{300}{}{What is your name.. RAZOR?! }
{350}{}{Grrrr.. Woof! }

{400}{}{What is your name stupid dog?! }
{450}{}{[He "smiling" and it seem that its name is "stupid dog". This dog look very hungry.. and you wonder how he could helpfull when you bring him some meat..] }

{500}{}{Hey you, stupid dog! Take this! [throw him meat] }
{550}{}{Grrr.. wof! wof! [He take meat and run behind house to hide it under sand.. and you see that its many items inside hole which he dig. Rags, bones, few coins and.. golden watch!] }

{910}{}{ ŒÕ≈÷ }
{920}{}{Õ¿«¿ƒ }

