
{10}{}{Милашка Изабель.}
{20}{}{Одна из порно звезд, работающих в Ванных.}

{50}{}{ ааа }
{51}{}{ ббб }
{52}{}{ ввв }
{53}{}{ ггг }
{54}{}{ ддд }

{100}{}{Привет, незнакомец. Хочешь... провести время приятно?}

{200}{}{Почему ты одет в комбинезон, ты житель убежища?}
{250}{}{Ээ... нет... я купил его давным давно, потому что мне нравится синий цвет... наверно он принадлежал какому-то жителю, но я не уверен. В любом случае, я не верю во все это Убежище Будущего, никто не знает где этот... секретный бункер.}

{300}{}{Ты можешь говорить быстрее?}
{350}{}{[Она облизывает свои сексуальные губы и говорит очень чувственным голосом]. Милый, я готова... у тебя есть наличка? [Она садится на кровать и кладет ногу на ногу]. Тебе нравится мой... парфюм?}

{400}{}{У тебя есть пиво?}
{450}{}{Милый, я не пью пиво... Спроси Сильвию... [она берет красный цветок с кровати и нюхает его]. Но если тебе попадутся наркотики... поделись, пожалуйста.}

{500}{}{Когда вы заходите в комнату, она уже обнажилась и заняла свою любимую позицию. Вы приступаете в спешке, потому что у вас есть 30 минут с ней.}

{501}{}{[В:05] }
{502}{}{[В:10] }
{503}{}{[В:15] }
{504}{}{[В:20] }
{505}{}{[В:25] }
{506}{}{[В:30] ВРЕМЯ ВЫШЛО!}

{600}{}{You try to fix spring which jump out from bed.. }
{601}{}{You try to catch rat which run under bed..}
{602}{}{You drink water from glass..}
{603}{}{You open window and take deep breatch..}
{604}{}{You check corridor to be sure nobody hear you..}
{605}{}{You check window to be sure nobody see you..}
{606}{}{You lost concentration and fall on floor..}
{607}{}{Ants walking on bed and you try to catch them.. }
{608}{}{Dog scream from outside and deconcentrate you..}
{609}{}{You fall into confusion and escape from room..}
{610}{}{You got short heart attack and you feel tired.. }
{611}{}{You feel tired and you sit on chair to rest..}
{612}{}{Spider jump on your head and you fall in panic..}
{613}{}{You try to change her position, but you cant.. }
{614}{}{You kiss her wet and hot lips, she say "mmmmm".. }
{615}{}{She move her legs slowly and lick own tits..}
{616}{}{She say "Ooouuuh darling.. come on fill me!" }
{617}{}{You try to strip own socks but they stuck..}
{618}{}{You try to strip own shirt but it stuck..}
{619}{}{You touch her legs and she say "ouuh yees.."}
{620}{}{ }
{621}{}{ }
{622}{}{ }
{623}{}{ }

{700}{}{ pyt3 }

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

