
{10}{}{Страстная Полина.}
{20}{}{Одна из порнозвезд, работающих в Ванных комнатах.}

{50}{}{ ааа }
{51}{}{ ббб }
{52}{}{ ввв }
{53}{}{ ггг }
{54}{}{ ддд }

{100}{}{Hi. I seen you around, you are Klamath citizen, right? }

{200}{}{I like your style.}
{250}{}{[She seem to be very lucky and agile] Thanx. But sadly.. i dont like yours haha! Many peoples call me CAT. I was thief once, member of Yakuza team. But i lost with them contact long time ago, so i hired in bathhouse to get some cash. Am not sure where they disappear and whats happend.. but it must be some tragic accident. Well, am still alive!  }

{300}{}{I dont remember my wife and kids, i must hit brain somewhere..}
{350}{}{Hah! No its probably because radiation. But dont be so sad, many peoples spend lot of money to be in your situation. I mean that wonderfull time when you forgot everything.. and dont care about whole problems! }

{400}{}{Do you have beer?}
{450}{}{Here? No! I dont have fridge, you known.. hot beer tasty ugly! If you need some drinks go to Arroyo, i heard that local shaman make very good "Schlager". Just one drink of that mixture and you fly away! Sadly it dont smell good, i wonder from what its made anyway!? }

{500}{}{Когда вы заходите в комнату, она уже обнажилась и заняла свою любимую позицию. Вы приступаете в спешке, потому что у вас есть 30 минут с ней.}

{501}{}{[В:05] }
{502}{}{[В:10] }
{503}{}{[В:15] }
{504}{}{[В:20] }
{505}{}{[В:25] }
{506}{}{[В:30] ВРЕМЯ ВЫШЛО!}

{600}{}{Вы пытаетесь починить пружину, выскочившую из кровати.}
{601}{}{Вы пытаетесь поймать крысу, пробежавшую по кроватью.}
{602}{}{Вы пьете воду из стакана.}
{603}{}{Вы открываете окно и делаете глубокий вдох.}
{604}{}{Вы проверяете коридор, чтобы убедиться, что вас никто не слышит.}
{605}{}{Вы проверяете окно, чтобы убедиться, что не вас никто не смотрит}
{606}{}{Вы теряете концентрацию и падаете на пол.}
{607}{}{Муравьи бегают по кровати, и вы пытаесь их поймать.}
{608}{}{Снаружи воет собака и отвлекает вас.}
{609}{}{Вы смущаетесь и оставляете комнату.}
{610}{}{У вас небольшой сердечный приступ, и вы устали.}
{611}{}{Вы устали и присаживаетесь на стул, чтобы отдохнуть.}
{612}{}{Паук прыгает вам на глову, и в панике, вы падаете.}
{613}{}{Вы пытаетесь заставить ее сменить позицию, но у вас не получается.}
{614}{}{Вы целуете ее в горячие и влажные губы, и она говорит "ммммммм".}
{615}{}{Она медленно двигает ногами и лижет свои сиськи.}
{616}{}{Она говорит "Ооооо, дорогой... наполни меня!"}
{617}{}{Вы пытаетесь снять свои носки, но у вас не получается.}
{618}{}{Вы пытаетесь снять свою рубашку, но застреваете в ней.}
{619}{}{Вы трогаете ее ноги, и она говоит "ооооо даа"}
{620}{}{ }
{621}{}{ }
{622}{}{ }
{623}{}{ }

{700}{}{ пит3 }

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

