
{10}{}{Samantha Wet. }
{20}{}{One from pornstars working for Bathhouse.}

{50}{}{ ааа }
{51}{}{ ббб }
{52}{}{ ввв }
{53}{}{ ггг }
{54}{}{ ддд }

{100}{}{[She seem to be very "experienced" and.. crazy] I will show you things which you never seen.. are you ready? Pay 30$ and come back.. am waiting for you..}

{200}{}{I have hole in my memories.}
{250}{}{Do you want to hear about my.. wet holes?}

{300}{}{Do you play in porn movies?}
{350}{}{Yes.. am real pornstar.. from New Reno. I hide here because i read notebook from one mafioso.. and he known about that! There was every payments, secret agents, drugs facility.. Damn! i was so stupid to steal it! Here i fell safety.. and they pay me not bad at all. I played in few movies, such like "Fill me twice" or "Mega tits vol3".. maybe you seen them? }

{400}{}{Uh.. i forgot what i wanted to ask you..}
{450}{}{Then come bak later.. i must get shower..}

{500}{}{Когда вы заходите в комнату, она уже обнажилась и заняла свою любимую позицию. Вы приступаете в спешке, потому что у вас есть 30 минут с ней.}

{501}{}{[В:05] }
{502}{}{[В:10] }
{503}{}{[В:15] }
{504}{}{[В:20] }
{505}{}{[В:25] }
{506}{}{[В:30] ВРЕМЯ ВЫШЛО!}

{600}{}{You try to fix spring which jump out from bed.. }
{601}{}{You try to catch rat which run under bed..}
{602}{}{You drink water from glass..}
{603}{}{You open window and take deep breatch..}
{604}{}{You check corridor to be sure nobody hear you..}
{605}{}{You check window to be sure nobody see you..}
{606}{}{You lost concentration and fall on floor..}
{607}{}{Ants walking on bed and you try to catch them.. }
{608}{}{Dog scream from outside and deconcentrate you..}
{609}{}{You fall into confusion and escape from room..}
{610}{}{You got short heart attack and you feel tired.. }
{611}{}{You feel tired and you sit on chair to rest..}
{612}{}{Spider jump on your head and you fall in panic..}
{613}{}{You try to change her position, but you cant.. }
{614}{}{You kiss her wet and hot lips, she say "mmmmm".. }
{615}{}{She move her legs slowly and lick own tits..}
{616}{}{She say "Ooouuuh darling.. come on fill me!" }
{617}{}{You try to strip own socks but they stuck..}
{618}{}{You try to strip own shirt but it stuck..}
{619}{}{You touch her legs and she say "ouuh yees.."}
{620}{}{ }
{621}{}{ }
{622}{}{ }
{623}{}{ }

{700}{}{ pyt3 }

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

