
{10}{}{Торговец водой.}
{20}{}{Похоже, он очень занят какой-то большой машиной.}

{100}{}{[Он пинает машину и ругается] НЕТ! Только не снова! Чертова куча мусора!}

{200}{}{У тебя есть пиво?}
{250}{}{Нет, у меня есть только минеральная вода из подземного источника... ну или была, пока эта рухлядь не начала артачиться. Я думаю, это из-за водного чипа. Найди для меня один, и я дам тебе флягу невероятно чистой воды, такой чистой, что ты отлично себя почувствуешь, даже лучше, чем после десяти кружек пива. Я слышал, такие чипы можно найти в Убежищах.}

{300}{}{Water Chip? I think i got one..}
{350}{}{[He install Chip into machine and it work again, water swim into metall container called bathtub (you heard that its made to clean peoples, but you never used it) After bathtub was full he smile and say] Thank you! It seem to work now ok! Uh i forgot.. take this flask of fresh mineral water!}

{400}{}{Thats it! Delicious water!}
{401}{}{I will be rich again! YES!}
{402}{}{::DRINK::}
{403}{}{Wonderfull tasty!}
{404}{}{I must find some clean flasks.. }

{910}{}{КОНЕЦ }
{920}{}{НАЗАД }

