# coding: windows-1251
{10}{}{Den News. }
{20}{}{Множество грязных страниц, прикрепленных к куску дерева...}
{100}{}{=== DEN = NEWS === }
{200}{}{"Геройский Джет" ВСЕГО ПО 20 баксов!!!}
{250}{}{ПОТРЯСАЮЩЕЕ Несколько дней назад я изобрел мощный препарат, который поможет вам почувствовать себя НАСТОЯЩИМ героем! ВСЕГО ЛИШЬ $20, приходите ко мне домой, у меня его много в запасе. Вы сможете стать Бэтмэном, Человеком Пауком или даже Чаком Норрисом! ПОТРЯСАЮЩЕЕ}
{300}{}{I found UFO near Navarro!}
{350}{}{I seen many unidentified obiects over Navarro base and i found few from them crased on desert. Pay me 3000$ and i will sell you that wonderfull vehicle! I have them THREE on my junkyard!}
{400}{}{JOIN TO ARMY TODAY }
{450}{}{We search new recruits to Brotherhood of Steel army. Visit our bunker in Den and talk with sir Marcus from Blood Raven squad. Earn richness and fame during battles against mutants! }
{910}{}{КОНЕЦ }
{920}{}{НАЗАД }
