# coding: windows-1251
{10}{}{Psychiatry. }
{20}{}{He look very clever..}
{100}{}{Lets begin tests. Situation first: someone want help, what you do? Situation second: you can fill backpack only by four items, what it is? Situation third: you found very powerfull drug, what you do?}
{200}{}{1. Я ему говорю "извини я занят"}
{250}{}{Стальная дверь.}
{300}{}{2. Четыре пива!}
{350}{}{Спасибо [он что-то отмечает на бумаге], давай вернемся к тесту.}
{400}{}{3. Я ем это и ищу еще!}
{450}{}{Спасибо [он что-то отмечает на бумаге], давай вернемся к тесту.}
{910}{}{КОНЕЦ }
{920}{}{НАЗАД }
