{10}{}{Bewachen.}
{20}{}{Sie, alle Stammesangehörigen, sehen gleich aus ..}
{100}{}{Hey! Du! Dreckiger Mann! Was machst du hier? Dieses Dorf ist streng geheim und niemand von außerhalb darf unser heiliges Land betreten!}
{200}{}{Ich bin nur ein Reisender aus Klamath.}
{250}{}{Verschwinde hier! Leute wie du kommen hierher, nur um alles zu stehlen und Probleme zu machen. Deshalb mögen wir keine Touristen!}
{300}{}{Hast du eine Flasche Bier?}
{350}{}{Was ist Bieee? Ich habe noch nie davon gehört.. Vielleicht hat unser verrückter Schamane eine, er hat viele seltsame Mischungen und Tränke.}
{400}{}{Ich suche etwas zu trinken... Was hast du?}
{450}{}{Unsere Hexe hat einen anderen Dorfbewohner in den Temple of Trails geschickt und ich muss ihn beobachten. Bisher ist noch niemand von dort zurückgekehrt. Wir brauchen einen mutigen Krieger, der eine gefährliche Aufgabe erfüllt und uns in diesen dunklen Tagen retten wird.}
{910}{}{Ende}
{920}{}{Zurück}
