{10}{}{Dalton. }
{20}{}{One from Dalton brothers, they are very similar..}
{100}{}{[He scream on his brother, then say] What you want?}
{200}{}{Uh.. whats going on?}
{250}{}{My brother lost keys to house AGAIN and he say that it was me! But he got these keys last time! I remember that clearly.. we go to bar and drink whole night.. i seen him when he thrown keys on barman!}
{300}{}{Habt ihr Bier?}
{350}{}{No i dont have and i DONT care about your problems!}
{400}{}{Do you remember me?}
{450}{}{Yes ofcourse.. you are local loser, this town is full of peoples like you, who have holes in memories because experiment too much with drugs and radioactive beers from "Gecko Plant"}
{910}{}{Ende}
{920}{}{Zurück}
