
{10}{}{Guard, really guard.}
{20}{}{They everyone tribals look the same..}

{100}{}{Hey! You! Dirty man! What you doing here?! This village is top secret and nobody from outside world cant enter our holy land! }

{200}{}{Am just traveller from Klamath. }
{250}{}{Get out of here! Peoples like you come here only to steal everything and make troubles. Thats why we dont like tourists!  }

{300}{}{Do you have flask of beer? }
{350}{}{What is beee? I never heard about such thing.. Maybe our crazy shaman will have one, he got many strange mixtures and potions.}

{400}{}{I search something to drink.. And what you do?}
{450}{}{Our witch put another villager to temple of trails and i must watch him. Already nobody returned from there. We need brave champion to made dangerous quest which will save us in these dark times.}

{910}{}{END }
{920}{}{BACK }
