


{10}{}{Chosen One. }
{20}{}{They everyone tribals look the same..}

{100}{}{Damn! I will die there.. i known that! }

{200}{}{Hi man! Whats up?}
{250}{}{Witch chosen me for test in temple. I fear to enter because nobody return.. can you hear this scream from darkness? Everyone died there. She must be really stupid to kill our brothers and sisters in this dumb test!}

{300}{}{Do you have beer?}
{350}{}{[He look into temple darkness and ignore your question]}

{400}{}{Am so thirsty! Maybe i will find some beer it this.. tample?}
{450}{}{Oh yes.. temple contain many treasures from ancient world. Now leave me alone! I must made first little step into darkness.. but i fear to move my leg.}

{910}{}{END }
{920}{}{BACK }






















