
{10}{}{Strange Folk. }
{20}{}{He look crazy..}

{100}{}{Let me shown you! [You hear voice of man hidden in small street, between corner and boxes. He is almost unvisible so first time you think that dog which stand near say something to you..] }

{200}{}{Uk.. ok shown me.}
{250}{}{Watch! [You see that he dont have any clothes under cloak! But he shown you so quick that you seen almost nothing.]}

{300}{}{What you want from me?!}
{350}{}{I will shown you! Just give me one coin!}

{400}{}{Do you have beer?}
{450}{}{I have something better.. WATCH! [He shown you his dirty body. You lost concentration, and almost fall on ground.] }

{910}{}{END }
{920}{}{BACK }

