


{10}{}{Paulina Hot. }
{20}{}{One from pornstars working for Bathhouse.}

{50}{}{ aaa }
{51}{}{ bbb }
{52}{}{ ccc }
{53}{}{ ddd }
{54}{}{ eee }


{100}{}{Hi. I seen you around, you are Klamath citizen, right? }

{200}{}{I like your style.}
{250}{}{[She seem to be very lucky and agile] Thanx. But sadly.. i dont like yours haha! Many peoples call me CAT. I was thief once, member of Yakuza team. But i lost with them contact long time ago, so i hired in bathhouse to get some cash. Am not sure where they disappear and whats happend.. but it must be some tragic accident. Well, am still alive!  }

{300}{}{I dont remember my wife and kids, i must hit brain somewhere..}
{350}{}{Hah! No its probably because radiation. But dont be so sad, many peoples spend lot of money to be in your situation. I mean that wonderfull time when you forgot everything.. and dont care about whole problems! }

{400}{}{Do you have beer?}
{450}{}{Here? No! I dont have fridge, you known.. hot beer tasty ugly! If you need some drinks go to Arroyo, i heard that local shaman make very good "Schlager". Just one drink of that mixture and you fly away! Sadly it dont smell good, i wonder from what its made anyway!? }


{500}{}{When you enter room she was naked in her favourite position and in hurry you begin action, because you got 30 minutes of time to spend with her.}

{501}{}{[T:05] }
{502}{}{[T:10] }
{503}{}{[T:15] }
{504}{}{[T:20] }
{505}{}{[T:25] }
{506}{}{[T:30] TIME END! }



{600}{}{You try to fix spring which jump out from bed.. }
{601}{}{You try to catch rat which run under bed..}
{602}{}{You drink water from glass..}
{603}{}{You open window and take deep breatch..}
{604}{}{You check corridor to be sure nobody hear you..}
{605}{}{You check window to be sure nobody see you..}
{606}{}{You lost concentration and fall on floor..}
{607}{}{Ants walking on bed and you try to catch them.. }
{608}{}{Dog scream from outside and deconcentrate you..}
{609}{}{You fall into confusion and escape from room..}
{610}{}{You got short heart attack and you feel tired.. }
{611}{}{You feel tired and you sit on chair to rest..}
{612}{}{Spider jump on your head and you fall in panic..}
{613}{}{You try to change her position, but you cant.. }
{614}{}{You kiss her wet and hot lips, she say "mmmmm".. }
{615}{}{She move her legs slowly and lick own tits..}
{616}{}{She say "Ooouuuh darling.. come on fill me!" }
{617}{}{You try to strip own socks but they stuck..}
{618}{}{You try to strip own shirt but it stuck..}
{619}{}{You touch her legs and she say "ouuh yees.."}
{620}{}{ }
{621}{}{ }
{622}{}{ }
{623}{}{ }





{700}{}{ pyt3 }








{910}{}{END }
{920}{}{BACK }






















