


{10}{}{Tricky kid! }
{20}{}{Everyone knowns this kid is VERY quick!}

{100}{}{[He read something in silence]}

{200}{}{Helo kid what you read?}
{201}{}{Do you have beer?}
{202}{}{Why you are so quick, do you eat something?}
{203}{}{Where is your parents?}
{204}{}{Damn! Whats wrong with you!?}

{250}{}{[He quickly remove one coin from your inventory and he do it so fast that you seen only blur shape trough one second and say] LOSER!}

{300}{}{i found}
{350}{}{[He make big eyes and scream] I EAT MUTATED FRUIT!}

{400}{}{r1}
{401}{}{r2}
{402}{}{r3}
{403}{}{r4}
{404}{}{r5}

{910}{}{END }
{920}{}{BACK }






















