
{10}{}{Some old man. }
{20}{}{He look very wise..}

{100}{}{Hello outsider.. are you Vic friend?}

{200}{}{I seen that man few times in Klamath. Once he sell me beer whis tasty like someone piss into bottle.}
{250}{}{So you dont like him? This village is separated into two groups, these who like traditions and thase who like technic items. Am from these who follow ancestor words which say that technic bring only pain and destruction..}

{300}{}{Are you elder?}
{350}{}{Yes, but we have many elders here: traditionalists and these who deal with outsiders like Vic. Probably you search witch who lately need champion for big quest. She is in tent to the south from here.}

{400}{}{Whats going around lately?}
{450}{}{Witch need brave man who will search some technical stuff. Its called GECK. Vic trader tell about it many weird stories. I think our situation will change into worst when someone find it. Whole sick problems which we got here is only because shaman inventions. Its dont need to fall into panic and make risky decisions.. }

{910}{}{END }
{920}{}{BACK }

