{10}{}{Guardia.}
{20}{}{Todos los tribales tienen el mismo aspecto.}
{100}{}{¡Oye! ¡Tú! ¡Sucio! ¡¿Qué haces aquí?! ¡Este pueblo es ultra secreto y nadie del mundo exterior puede entrar en nuestra tierra santa!}
{200}{}{Soy un viajero de Klamath.}
{250}{}{¡Fuera de aquí! Las personas como tú vienen aquí solo para robar y causar problemas. ¡Por eso no nos gustan los turistas!}
{300}{}{¿Tienes algo de cerveza?}
{350}{}{¿Qué es eso? Nunca lo había escuchado... Tal vez nuestro chamán loco tenga alguna, tiene muchas mezclas y pociones extrañas.}
{400}{}{Busco algo de beber... ¿Y tú que haces?}
{450}{}{Nuestra bruja puso a otro aldeano en el templo de los senderos y debo vigilarlo. Nadie ha regresado de allí. Necesitamos un campeón valiente para hacer una búsqueda peligrosa que nos salvará en estos tiempos oscuros.}
{910}{}{FIN}
{920}{}{REGRESAR}
