{10}{}{Elegido}
{20}{}{Todos los tribales tienen el mismo aspecto.}
{100}{}{¡Maldita sea! Voy a morir… ¡Lo sabía!}
{200}{}{¡Hola hombre! ¿Qué pasa?}
{250}{}{La bruja me eligió para una prueba en el templo. Tengo miedo de entrar porque nadie regresa… ¿Puedes escuchar los gritos desde la oscuridad? Todos murieron allí. ¡Debe ser realmente estúpida para matar a nuestros hermanos y hermanas en esta estúpida prueba!}
{350}{}{[Él mira la oscuridad del templo ignorando tu pregunta]}
{400}{}{¡Tengo tanta sed! Tal vez encuentre algo de cerveza en este… ¿"Tempro"?}
{450}{}{Oh, sí… el templo contiene muchos tesoros del mundo antiguo. ¡Ahora déjame solo! Debo dar el primer paso hacia la oscuridad… pero mi pierna no responde.}
{910}{}{FIN}
{920}{}{REGRESAR}
