{10}{}{Aldeano.}
{20}{}{Todos aquí tienen el mismo aspecto.}
{100}{}{Hola extraño… ¿Escuchas esa extraña voz que emana del pozo?}
{200}{}{Sí… suena como a ladridos de un perro.}
{250}{}{No… creo que es algo diferente. Debe ser un antiguo fantasma de la tierra… que necesita un sacrificio hecho con el elemento tierra. Ve al campo de maíz y tráeme una piedra grande.}
{300}{}{¡Mira! Encontré una.}
{350}{}{¡Aquí, un sacrificio para los dioses de la tierra! [El aldeano arroja la piedra al pozo y después de un breve grito permanece en un silencio eterno.] Gracias, amigo mío, ahora el fantasma de la tierra está feliz y cesando los gritos. Aquí está tu recompensa, una maravillosa flor que tuvo un buen crecimiento.}
{400}{}{¡Ahora somos bendecidos por la tierra!}
{401}{}{¡Algunas moscas alrededor de la buena magia!}
{402}{}{Bendito silencio.}
{403}{}{Ugh… ¿Qué es ese olor?}
{404}{}{¡Gracias mi amigo!}
{910}{}{FIN}
{920}{}{REGRESAR}
