{10}{}{Aldeano.}
{20}{}{Todos aquí tienen el mismo aspecto.}
{100}{}{¡Perdí a mi perro y temo que alguien se lo coma! Forastero, ¿Puedes investigar a dónde fue mi sucio animal? Su nombre era "Klint".}
{200}{}{No me gustan los acertijos.}
{250}{}{Uh, sí… no pareces muy inteligente. No importa, esperaré aquí hasta que regrese. Probablemente corrió por el pueblo cazando ratas.}
{300}{}{¿Tienes algo de cerveza?}
{350}{}{[Mira a su alrededor buscando perro e ignora tu pregunta]}
{400}{}{Háblame de este pueblo.}
{450}{}{Vivimos en paz lejos de la civilización. Los ancianos dicen que la técnica solo trae dolor y devastación, por lo que debemos creer solo en la magia tradicional de los chamanes. Pero un día vino un comerciante llamado Vic, con sus increíbles cosas. Los fantasmas santos nos abandonan y muchos pueblos se enferman.}
{910}{}{FIN}
{920}{}{REGRESAR}
