{10}{}{Aldeano.}
{20}{}{Todos aquí tienen el mismo aspecto.}
{100}{}{¡No lo puedo creer! Has superado la prueba, ¡Nadie lo había hecho! ¡Ahora eres nuestro campeón!. Ve y habla con la anciana, ella tiene algo muy importante que decirte.}
{200}{}{Uh… ¿Eres el guardia de la entrada del templo? Siento que todos los tribales son iguales.}
{250}{}{Sí, soy el guardia y un gran guerrero, "Klint". Por cierto, odio a este bastardo que llamó a su perro con mi nombre. Ojalá pueda solucionar el problema de ayer para ahora sentirme mejor.}
{300}{}{¿Y qué pasó con el tipo que le teme a entrar?}
{350}{}{Se escapó a través del bosque en las afueras de la aldea, de la misma manera de la que tú vienes. ¡Espero que nunca regrese, no me gustan los cobardes!}
{400}{}{¡Sí, soy un héroe! ¡Ahora dame cerveza!}
{450}{}{Lo siento, pero no sé qué es eso… Habla con la anciana, ella sabe muchas cosas sobre los artefactos sagrados. También hace tratos con el comerciante Vic, él nos trae muchas cosas extrañas del mundo exterior.}
{910}{}{FIN}
{920}{}{REGRESAR}
