{10}{}{Aldeano.}
{20}{}{Todos aquí tienen el mismo aspecto.}
{100}{}{Estoy cansada… ¡Oye, sucio! ¡¿Puedes ayudarme?!}
{200}{}{No estoy seguro… pero ¿Qué necesitas?}
{250}{}{Necesito entregarle más mierda al Chamán, pero mi pala es muy pesada. Tráeme una nueva y limpia. ¡Debería estar en algún lugar cerca de las tiendas de campaña! [Señala con el dedo en una dirección aleatoria y se sienta en el suelo tratando de limpiar los zapatos]}
{300}{}{¡Encontré una pala limpia!}
{350}{}{Gracias chico… terminaré mi trabajo más tarde, porque estoy muy cansada. Toma estas cosas brillantes que Vic me dio por un beso. Escuché que muchas cosas se pueden comprar por algo llamado… "dinero".}
{400}{}{Estoy cansada.}
{401}{}{Huelo a brahmin.}
{402}{}{¡Maldita sea! ¡Cómo pesan mis zapatos!.}
{403}{}{Otro día maravilloso.}
{404}{}{Estoy ocupada, déjame sola.}
{910}{}{FIN}
{920}{}{REGRESAR}
