{10}{}{Chamán.}
{20}{}{Tiene aspecto de un loco.}
{100}{}{¡Jajajaja… mira esas formas y colores!}
{200}{}{¿De qué estás hablando?}
{250}{}{¡Jajajaja… lo siento, olvidé que no ves lo que yo veo! Inventé una mezcla maravillosa. Está hecha de mierda de brahmin y flor de broquia. A menos que no tenga demasiadas flores. ¡Tráeme una y te ayudaré a ver el lado oculto del mundo asombroso!}
{300}{}{Tengo la flor, ¿Puedes hacerme la mezcla maravillosa?}
{350}{}{¡Oh sí! [Te quita la flor y un pedazo de mierda del barril. Después de media hora te dio una mezcla maravillosa.]}
{400}{}{¡Ayúdame! ¡El pájaro serpiente ataca mi zapato!}
{401}{}{¡¿Por qué estas rocas se me escapan?!}
{402}{}{¡Wow, tengo tres manos!}
{403}{}{¡¿Qué es eso?!… ¡¡No puedo atraparlo!!}
{404}{}{¡Fuego! ¡Mi casa se está quemando!}
{910}{}{FIN}
{920}{}{REGRESAR}
