{10}{}{Vitold. }
{20}{}{He seem to be one from your seven childrens..}
{100}{}{What damage made my sword? }
{101}{}{I open chest, what is inside? }
{102}{}{Run! I escape! }
{103}{}{Ok i enter house and what now? }
{104}{}{What is better bow or crossbow? }
{105}{}{Am unvisible! My cloak is black like night! }
{106}{}{Ok i throw him money!}
{107}{}{Thef? Where? Why i dont seen him??}
{108}{}{Damn! I should lear that skill in Koldsberg!}
{109}{}{What is name of that village?}
{110}{}{Ok am dirty but i got skill to find water so am clean! }
{111}{}{Yes am wounded but i fall into berserk so i dont feel it! }
{112}{}{How big is that forest? }
{113}{}{So you use pathfinding and me watch on trees! }
{114}{}{I see something on ground because i got perception level3 }
{115}{}{No! It must be something there! }
{116}{}{No.. am not cheating.. }
{117}{}{So what she say? }
{118}{}{I dont care because i wear metal armor..}
{119}{}{No my sword will never broke! I got smith skill level5 }
{120}{}{Hah! THIS was funny! }
{121}{}{So what i could do?? I tryed everything!! }
{122}{}{Uh.. i dont seen it. }
{123}{}{Where is my blue dice? My favourite! }
{124}{}{Can i use condom as holy artefact? }
{125}{}{But players can use items from other games! }
{126}{}{Its balloon made from alien robot hehe! }
{127}{}{No am not! }
{128}{}{Am enter tavern and scream BEER! }
{129}{}{He was drunken? I think he was dead! }
{130}{}{Am sit on horse and run trough corridor to exit! }
{131}{}{No! YOU are sick! }
{132}{}{So i open chest but i quickly hide my eyes! }
{133}{}{Blind?! So what now?! }
{134}{}{And what about skill translater? }
{135}{}{Animals got also language.. its BODY language! }
{136}{}{HA HA HA! }
{137}{}{I do nothing! Am just sit on ground.. }
{138}{}{No you dont understand! Its NEW skill! }
{139}{}{Yes i can! Yes i can! Yes i can! }
{140}{}{No! No! No!.. Shut up! }
{141}{}{Hah i WIN! }
{142}{}{How much i get experience? }
{143}{}{Ok i spend three skillpoints on bravery. }
{144}{}{Bravery mean bonus during battle based on level of that skill. }
{145}{}{Yes its best rule: bonus based on level of that skill add to throws. }
{146}{}{Normal throws will be 1k6 and everything else bonus! }
{147}{}{So what we will use only one dice, our favourite! }
{148}{}{Yeah! And player can invent any skill he want DURING game! }
{149}{}{Situations mean you will get bad effects high as situation LEVEL! }
{150}{}{Uh am not sure.. it could be for example ten levels. It mean 100% }
