{10}{}{Water Merchant. }
{20}{}{He seem to be very busy on some big machine..}
{100}{}{[He kick machine and say] NO! Not again! Damn junk!}
{200}{}{¿Tienes algo de cerveza?}
{250}{}{No i got only mineral water from deep underground source.. unless last days this old machine work weird. I think its because water chip. Find me one and i will give you flask of amazing clean water, its so clean that you will get wonderfull feelings.. even better than after ten beers. I heard these chips can be found inside Vaults.}
{300}{}{Water Chip? I think i got one..}
{350}{}{[He install Chip into machine and it work again, water swim into metall container called bathtub (you heard that its made to clean peoples, but you never used it) After bathtub was full he smile and say] Thank you! It seem to work now ok! Uh i forgot.. take this flask of fresh mineral water!}
{400}{}{Thats it! Delicious water!}
{401}{}{I will be rich again! YES!}
{402}{}{::DRINK::}
{403}{}{Wonderfull tasty!}
{404}{}{I must find some clean flasks.. }
{910}{}{FIN}
{920}{}{REGRESAR}
