{10}{}{Psychiatry. }
{20}{}{He look very clever..}
{100}{}{Lets begin tests. Situation first: someone want help, what you do? Situation second: you can fill backpack only by four items, what it is? Situation third: you found very powerfull drug, what you do?}
{200}{}{1. Am tell him "sorry am busy" }
{250}{}{Thanx [he mark something on paper] lets return to test. }
{300}{}{2. Four beers!}
{350}{}{Thanx [he mark something on paper] lets return to test. }
{400}{}{3. I eat it and search more! }
{450}{}{Thanx [he mark something on paper] lets return to test. }
{910}{}{FIN}
{920}{}{REGRESAR}
