{10}{}{Isabell Sweet. }
{20}{}{One from pornstars working for Bathhouse.}
{50}{}{ aaa }
{51}{}{ bbb }
{52}{}{ ccc }
{53}{}{ ddd }
{54}{}{ eee }
{100}{}{Hello stranger.. do you need some.. sweet time? }
{200}{}{Why you wear jumpsuit, are you vault citizen?}
{250}{}{Uh.. no, am not.. i buy it long time ago because i like blue colour.. probably it belong to some citizen, but am not sure. Well.. i dont believe in whole Vault of Future, nobody know where is this.. secret bunker.}
{300}{}{Can you talk faster?}
{350}{}{[She lick slowly her sexy lips and say very sensitive] Sweetheart, am ready for.. action.. do you have some cash? [Then she sit on bed and put one leg on other] Do you like my.. perfumes?}
{400}{}{Do you have beer?}
{450}{}{Honey.. i dont drink beer.. Ask Sylvia.. [she take red flower which lay on bed and smell it] But if you will find any drugs.. give me some.. please..}
{500}{}{When you enter room she was naked in her favourite position and in hurry you begin action, because you got 30 minutes of time to spend with her.}
{501}{}{[T:05] }
{502}{}{[T:10] }
{503}{}{[T:15] }
{504}{}{[T:20] }
{505}{}{[T:25] }
{506}{}{[T:30] TIME END! }
{600}{}{You try to fix spring which jump out from bed.. }
{601}{}{You try to catch rat which run under bed..}
{602}{}{You drink water from glass..}
{603}{}{You open window and take deep breatch..}
{604}{}{You check corridor to be sure nobody hear you..}
{605}{}{You check window to be sure nobody see you..}
{606}{}{You lost concentration and fall on floor..}
{607}{}{Ants walking on bed and you try to catch them.. }
{608}{}{Dog scream from outside and deconcentrate you..}
{609}{}{You fall into confusion and escape from room..}
{610}{}{You got short heart attack and you feel tired.. }
{611}{}{You feel tired and you sit on chair to rest..}
{612}{}{Spider jump on your head and you fall in panic..}
{613}{}{You try to change her position, but you cant.. }
{614}{}{You kiss her wet and hot lips, she say "mmmmm".. }
{615}{}{She move her legs slowly and lick own tits..}
{616}{}{She say "Ooouuuh darling.. come on fill me!" }
{617}{}{You try to strip own socks but they stuck..}
{618}{}{You try to strip own shirt but it stuck..}
{619}{}{You touch her legs and she say "ouuh yees.."}
{620}{}{ }
{621}{}{ }
{622}{}{ }
{623}{}{ }
{700}{}{ pyt3 }
{910}{}{END }
{920}{}{BACK }
