{10}{}{Vakt.}
{20}{}{De allihop stammedlemmar ser likadana ut..}
{100}{}{Hörru du! Smutsgubbe! Vad gör du här?! Den här byn är topphemlig och ingen från världen utanför får komma in i vårt heliga land!}
{200}{}{Är bara resenär från Klamath.}
{250}{}{Stick härifrån! Folk som du kommer hit bara för att stjäla allt och starta trubbel. Det är därför vi inte gillar turister!}
{300}{}{Har du en flaska öl?}
{350}{}{Vad är bii? Jag har aldrig hört om något sånt.. Kanske vår galna shaman har ett, han har många konstiga blandningar och trolldrycker.}
{400}{}{Jag söker efter något att dricka.. Och vad du gör?}
{450}{}{Vår häxa har satt en annan bybo i stigarnas tempel och jag måste hålla ett öga på honom. Än har ingen återvänt därifrån. Vi behöver modiga mästare som kan göra ett farligt uppdrag som kommer att rädda oss i dessa mörka tider.}
{910}{}{SLUT}
{920}{}{TILLBAKA}
