{10}{}{Den utvalda.}
{20}{}{De allihop stammedlemmar ser likadana ut..}
{100}{}{Fan! Jag kommer att dö där... jag visste det!}
{200}{}{Hej, mannen! Hur är läget?}
{250}{}{Häxan väljde mig till testet i templet. Jag e rädd för å gå in för ingen kommer tillbaks... kan du höra skriket från mörkret? Alla dog där. Hon måste vara riktigt dum om hon dödar våra bröder och systrar i detta dumma test!}
{300}{}{Har du öl?}
{350}{}{[Han tittar in i tempelmörkret och ignorerar din fråga]}
{400}{}{Är så törstig! Kanske hittar jag lite öl i det här... tamplet?}
{450}{}{Åh ja, templet innehåller många skatter från den antika världen. Lämna mig nu ifred! Jag måste ta det första lilla steget in i mörkret.. men jag är rädd för att röra på mitt ben.}
{910}{}{SLUT}
{920}{}{TILLBAKA }
