{10}{}{Bybo.}
{20}{}{De alla ser likadana ut..}
{100}{}{Halå främling.. hör du den där konstiga rösten från brunn??}
{200}{}{Ja, det låter som hundskrik.}
{250}{}{Nej, jag tror att det är något annat. Det måste vara ett gammalt spöke från jorden..  och han behöver ett offer av jordelement. Gå till majsfeltet och hämta någon stor sten...}
{300}{}{Titta! Jag har hittat en.}
{350}{}{Here is sacrifice for goddes of earth! [Villager throw that stone into well and after short scream remain ethernal silence.] Thank you my friend, now ghost of earth is happy and dont scream anymore. Here is your revard, wonderfull flower which grown near well.}
{400}{}{We are now bless by earth!}
{401}{}{So many flies around magic well!}
{402}{}{Blessed silence.}
{403}{}{Uh.. what is that smell?}
{404}{}{Thank you my friend!}
{910}{}{SLUT}
{920}{}{TILLBAKA}
