{10}{}{Bybo. }
{20}{}{De alla ser likadana ut..}
{100}{}{Halå främling.. hör du den där konstiga rösten från brunn??}
{200}{}{Ja, det låter som hundskrik.}
{250}{}{Nej, jag tror att det är något annat. Det måste vara ett gammalt spöke från jorden..  och han behöver ett offer av jordelement. Gå till majsfeltet och hämta någon stor sten...}
{300}{}{Titta! Jag har hittat en.}
{350}{}{Här är ett offer för jordens gudinna! [Byborna kastar stenen i brunnen och efter ett kort skrik förblir det eterisk tystnad.] Tack min vän, nu är jordens spöke lycklig och skriker inte längre. Här är din belöning, en underbar blomma som vuxit nära brunnen.}
{400}{}{Vi är nu välsignade av jorden!}
{401}{}{Så många flugor runt magisk brunn!}
{402}{}{Välsignad tystnad.}
{403}{}{Eh.. Vad är det som luktar?}
{404}{}{Tack, min vän!}
{910}{}{SLUT}
{920}{}{TILLBAKA }
