{10}{}{Bybo.}
{20}{}{De alla ser likadana ut..}
{100}{}{Halå främling.. hör du den där konstiga rösten från brunn??}
{200}{}{Ja, det låter som hundskrik.}
{250}{}{No i think its something different. It must be ancient ghost of earth..  and he need sacrifice made from earth element. Go on corn filed and bring me some big stone..}
{300}{}{Look! I found one.}
{350}{}{Here is sacrifice for goddes of earth! [Villager throw that stone into well and after short scream remain ethernal silence.] Thank you my friend, now ghost of earth is happy and dont scream anymore. Here is your revard, wonderfull flower which grown near well.}
{400}{}{We are now bless by earth!}
{401}{}{So many flies around magic well!}
{402}{}{Blessed silence.}
{403}{}{Uh.. what is that smell?}
{404}{}{Thank you my friend!}
{910}{}{SLUT}
{920}{}{TILLBAKA}
