{10}{}{Bybo.}
{20}{}{De alla ser likadana ut..}
{100}{}{Jag förlorade min hund. Uh... och jag är rädd att någon ska äta upp honom! Utböling, kan du undersöka vart mitt smutsiga djur tagit vägen? Han hette "Klint".}
{200}{}{Jag gillar inte att lösa gåtor.}
{250}{}{Ja, du ser inte särskilt smart ut. Strunt samma, jag ska bara vänta här tills han kommer tillbaka. Troligen springer han runt i byn och jagar råttor.}
{300}{}{Har du öl?}
{350}{}{[Han ser sig omkring och letar efter hund och ignorerar din fråga]}
{400}{}{Berätta om den här byn.}
{450}{}{We live in peace far from civilization. Elders say that technic bring only pain and devastation so we must believe only in traditional shamans magic. But one day come to us trader Vic with his amazing stuff. Holy ghosts abandon us and many peoples get sick. }
{910}{}{SLUT}
{920}{}{TILLBAKA}
