{10}{}{Bybo. }
{20}{}{De alla ser likadana ut..}
{100}{}{Jag kan inte tro det! Du passerar genom templet, ingen har gjort det förut! Du är nu vår kämpe! Gå och prata med den äldste, hon har något mycket viktigt att berätta för dig.}
{200}{}{Uh... är du den här vakten som jag såg nära tempelingången? Jag är ledsen att alla stamfolk ser likadana ut för mig.}
{250}{}{Ja, jag är vakt och stor krigare "Klint" Förresten hatar jag den här jäveln som kallar sin hund för mitt namn. Förhoppningsvis löste jag det problemet i går och jag känner mig bättre nu.}
{300}{}{Och vad hände med killen som är rädd för att gå in?}
{350}{}{Han flydde genom skogen utanför byn, på samma sätt som du kom hit. Jag hoppas att han aldrig kommer tillbaka, för jag gillar inte förlorare!}
{400}{}{Ja är hjälte! Ge mig öl nu!}
{450}{}{Jag är ledsen, men jag vet inte vad det är... Prata med den äldre, hon vet mycket om heliga artefakter. Och hon har att göra med handelsmannen Vis som tar med sig många märkliga saker från omvärlden.}
{910}{}{SLUT}
{920}{}{TILLBAKA }
