{10}{}{Bybo. }
{20}{}{De alla ser likadana ut..}
{100}{}{Är så trött. Hej smutsig man! Kan du hjälpa mig?!}
{200}{}{Eh är inte säker.. vad du behöver?}
{250}{}{Shaman vill ge honom mer skit, men min spade är så tung. Ge mig ny, ren spade. Den bord ligga någonstans nära tält där borta! [Hon pekar fingret i en slumpmässig riktning och sitt på marken och försöker rengöra skor].}
{300}{}{Jag hittade ren spade!}
{350}{}{Tack... jag kommer att avsluta mitt arbete senare, eftersom är för trött. Ta denna skinande saker som Vic gedde mig för en kyss. Jag har hört att man kan köpa många saker för sådan sak som kallas.. "pengar".}
{400}{}{Är så trött..}
{401}{}{Jag luktar som brahmin..}
{402}{}{Förbannat jag har tunga skor..}
{403}{}{Ännu en underbarr dag..}
{404}{}{Lämna mig ifred, är upptagen..}
{910}{}{SLUT}
{920}{}{TILLBAKA }
