{10}{}{Bybo.}
{20}{}{De alla ser likadana ut..}
{100}{}{Am so tired.. Hey dirty man! Can you help me?!}
{200}{}{Uh am not sure.. what you need?}
{250}{}{Shaman want to deliver him more shit, but my shovel is so heavy. Bring me new, clean one. It shold lay somewhere near tents over there! [She point finger in random direction and sit on ground trying to clean shoes]}
{300}{}{I found clean shovel!}
{350}{}{Thanx man.. i will finish my job later, because am too tired. Take this shining items which Vic gived me for one kiss. I heard that many things can be buy for such thing called.. "money".}
{400}{}{Am so tired..}
{401}{}{I smell like brahmin..}
{402}{}{Damn i have heavy shoes..}
{403}{}{Another wonderfull day..}
{404}{}{Leave me alone, am busy..}
{910}{}{SLUT}
{920}{}{TILLBAKA}
