{10}{}{Shaman. }
{20}{}{Han se verkligen galen ut..}
{100}{}{Hahahah... titta på dessa former och färger!!}
{200}{}{Eh.. Vad du pratar om?}
{250}{}{Hahahah.. förlåt jag glömde att du inte ser vad jag ser! Jag uppfann underbarr blandning. Den är gjord av brahminskit och brocblomma. Så länge jag inte har för många blommor. Ge mig en så kan hjälpa dig att se den gömda sidan av fantastisk värld!}
{300}{}{Jag har blomma, kan du göra denna blandning åt mig?}
{350}{}{Åh ja! [Han ta blomma från dig och bit skit från tunna. Efter halvtimme gedde han dig underbarr blandning.]}
{400}{}{Hjälp mig! Orm fågel attackera min sko!}
{401}{}{Varför dessa stenar flyr från mig?!}
{402}{}{Wow jag har tredje hand!!}
{403}{}{Vad är det där?! Jag kante fånga det!!}
{404}{}{Eld! Mitt hus är under eld!!}
{910}{}{SLUT}
{920}{}{TILLBAKA }
