{10}{}{Shaman. }
{20}{}{Han se verkligen galen ut..}
{100}{}{Hahahah... titta på dessa former och färger!!}
{200}{}{Eh.. Vad du pratar om?}
{250}{}{Hahahah.. sorry i forgot that you dont see what i see! I invented wonderfull mixture. Its made from brahmin shit and broc flower. Unless i dont have too much flowers. Bring me one and i will help you to see hidden side of amazing world!}
{300}{}{I got flower, can you made this mixture for me?}
{350}{}{Oh yeah! [He take flower from you and piece of shit from barrel. After half hour he gived you wonderfull mixture.]}
{400}{}{Help me! Snake bird attack my shoe!}
{401}{}{Varför dessa stenar flyr från mig?!}
{402}{}{Wow jag har tredje hand!!}
{403}{}{Vad är det där?! Jag kante fånga det!!}
{404}{}{Eld! Mitt hus är under eld!!}
{910}{}{SLUT}
{920}{}{TILLBAKA }
