{100}{}{Du har en fantastiskk syn men känner dig sjuk. }
{101}{}{Är herr fluga! Och är snabb som vind!  }
{102}{}{Var är min skor? Polisen! Någon stjäla mina skor!!  }
{103}{}{Wow... mitt huvud är så STORT!  }
{104}{}{Jag hittade guld! hahah! ...nej detär sten. }
{105}{}{Titta på den här regnbågen!!}
{106}{}{Jag kante röra mitt ben! Argh!!! Hjälp mig! }
{107}{}{Vadär fel med mina fingrar? Jag har dem för mycket... }
{108}{}{Är onsynlig! }
{109}{}{Är snabbare än kula! Wow jag rör mig så snabbt! }
{110}{}{Var är min schlager?! Eh.. jag har den i hand..}
{111}{}{Vad är det där på himlen? detär UFO?  }
{112}{}{Arrgh! Ormråtta äta mina skor!  }
{113}{}{Är så stor! Jag skulle kunna krossa dig av mitt finger!}
{114}{}{Why my pants are suddenly so wet?! }
{115}{}{Hey! You! Birdhead! Come on! }
{116}{}{I think i could jump over house.. }
{117}{}{Am rabbit.. I want to climb on tree! }
{118}{}{Mouse?! I have mouse in pocket!  }
{119}{}{Why these rocks watch at me?! }
{120}{}{I lost my hat!! Uh.. do i have hat before?  }
{121}{}{Where is my hairs?! Uh.. i got them in pocket!  }
{122}{}{Damn! My Schlager is empty!  }
{123}{}{Everything so slowly.. Hey you! Come on!  }
{124}{}{Yeah i like that music!!!  }
{125}{}{What you want from me?! Fuck off damn rat! }
{126}{}{What these flies want from me?! }
{127}{}{Vad denna hund säger?!}
{128}{}{WoW! My hand is so long!! }
{129}{}{Why am so green?! Oh no am supermutant!!  }
{130}{}{Polis! Kanin stjäl mina fingrar!! }
