{100}{}{Du har en fantastiskk syn men känner dig sjuk. }
{101}{}{Är herr fluga! Och är snabb som vind!  }
{102}{}{Var är min skor? Polisen! Någon stjäla mina skor!!  }
{103}{}{Wow... mitt huvud är så STORT!  }
{104}{}{Jag hittade guld! hahah! ...nej detär sten. }
{105}{}{Titta på den här regnbågen!!}
{106}{}{Jag kante röra mitt ben! Argh!!! Hjälp mig! }
{107}{}{Vadär fel med mina fingrar? Jag har dem för mycket... }
{108}{}{Är onsynlig! }
{109}{}{Är snabbare än kula! Wow jag rör mig så snabbt! }
{110}{}{Var är min schlager?! Eh.. jag har den i hand..}
{111}{}{Vad är det där på himlen? detär UFO?  }
{112}{}{Arrgh! Ormråtta äta mina skor!  }
{113}{}{Är så stor! Jag skulle kunna krossa dig av mitt finger!}
{114}{}{Varför mina byxor är plötsligt så blöta?! }
{115}{}{Hallå! Du! Fågelhuvud! Kom igen! }
{116}{}{Jag tror att jag kan hoppa över hus.. }
{117}{}{Är kanin.. Jag vill klättra på träd! }
{118}{}{Mus?! Jag har mus i fickan!  }
{119}{}{Varför dessa stenar kolla mot mig?!}
{120}{}{Jag tappade min hatt!! Eh.. har jag hatt förut?  }
{121}{}{Var är mina hår?! Eh.. jag har dem i ficka!  }
{122}{}{Jävlar! Min schlager är tom!  }
{123}{}{Allting så sakta... Hallå där! Kom igen!  }
{124}{}{Ja jag gillar den musiken!!  }
{125}{}{What you want from me?! Fuck off damn rat! }
{126}{}{What these flies want from me?! }
{127}{}{Vad denna hund säger?!}
{128}{}{WoW! My hand is so long!! }
{129}{}{Why am so green?! Oh no am supermutant!!  }
{130}{}{Polis! Kanin stjäl mina fingrar!! }
