{10}{}{Bybo. }
{20}{}{De alla ser likadana ut..}
{100}{}{Finally! After many years i finished this.. monument!}
{200}{}{Hur du gjorde det?}
{250}{}{Our elders dont allow us to use any technical stuff. With Vic drill i could made it in few days but i used traditional tool: wooden fork. I spend half of my life to made it, but as you see result was worth it.}
{300}{}{Vad är detta ansikte?}
{350}{}{Its me! Dont you see that? Uh maybe you dont see it.. because am old now, but its me. Its my face when i got 40 years.}
{400}{}{Varför du gjorde det?}
{450}{}{Why?! Such a stupid question! Because i could be most popular in whole village. Just imagine my big stone face in middle of village! Sadly only our shaman understand my monumental idea.}
{910}{}{SLUT}
{920}{}{TILLBAKA }
