{10}{}{Bybo. }
{20}{}{De alla ser likadana ut..}
{100}{}{Äntligen! Efter många år blev jag klar med detta.. monument!}
{200}{}{Hur du gjorde det?}
{250}{}{Våra Äldsta tilåter oss inte att använda några tekniska saker. Med Vicborr kunde jag göra på några dagar men jag använde traditionellt verktyg: trägaffel. Jag spendera halva mitt liv för att göra det, men som du ser resultat var värt det.}
{300}{}{Vad är detta ansikte?}
{350}{}{Its me! Dont you see that? Uh maybe you dont see it.. because am old now, but its me. Its my face when i got 40 years.}
{400}{}{Varför du gjorde det?}
{450}{}{Why?! Such a stupid question! Because i could be most popular in whole village. Just imagine my big stone face in middle of village! Sadly only our shaman understand my monumental idea.}
{910}{}{SLUT}
{920}{}{TILLBAKA }
