{10}{}{Frank. }
{20}{}{He seem to be one from your seven childrens..}
{100}{}{Look what i found inside trashcan! Delicious meat!}
{200}{}{Wow, good boy! Now give me piece, am hungry!}
{250}{}{No i will not! Bring me lighter and i will think about share with you anything. I have some cigaretes and now i want lighter! And dont look at me that way am old man! Am 10 years old!}
{300}{}{Here is lighter, now give me meat!}
{350}{}{Hah! Thanx! (He gived you some dry meat of dead rat.]}
{400}{}{Röker heheh!}
{401}{}{Vad du vill?!}
{402}{}{Lämna mig ifred!}
{403}{}{Ja jag har tändare!}
{404}{}{This trashcan is full ot treasures!}
{910}{}{SLUT}
{920}{}{TILLBAKA }
