{10}{}{Mark.}
{20}{}{He seem to be one from your seven childrens..}
{100}{}{Dragon wake up and look around..}
{101}{}{You are in dark cave..}
{102}{}{Suddenly something jump at your head!}
{103}{}{Deep and dark forest, you hear strange voice..}
{104}{}{And witch say that she known this secret..}
{105}{}{Throw one dice 1K6 for sword damage! }
{106}{}{Listen to ME am game master this time! }
{107}{}{2K6 for poison domage! Spider is very BIG!}
{108}{}{You cant move NOW! You are paralyzed!}
{109}{}{Hey! That corridor is too small to drive here on horse!!}
{110}{}{Damn! You cheating! Roll dices again!!}
{111}{}{Imagine whats happend now hehe! }
{112}{}{And on top of mountain is hidden silver sword of elves.. }
{113}{}{Elves silver is called Mithril.. or it was dwarven? }
{114}{}{Ashole! Am not playing with you! Roll dices again! }
{115}{}{You are human soldier age 19 }
{116}{}{So WHAT! Keep rules! }
{117}{}{What?! You cant talk with horse! }
{118}{}{Skill to create immortal potion? He must be alchemic level30 }
{119}{}{Haha.. you died! Because there was trap!! }
{120}{}{Robot? In medieval castle? }
{121}{}{Ok you have one implant made from silver.. }
{122}{}{Sorry but poeples without head cant be resurrect!}
{123}{}{Because you was shot by cannon! 6k6 damage! }
{124}{}{No! You walk slowly because you are wounded! }
{125}{}{This was poisonous frog so you died by kiss it! }
{126}{}{Suddenly thief steal all your money! }
{127}{}{Your chances of succes are 1k6+2 }
{128}{}{Yes its magical sword but its rusty and broken! Noramal damage 1k6! }
{129}{}{You move twice faster because you wear elven shoes. }
{130}{}{Wait! What you say? Tell me slowly i must count it! }
{131}{}{And you look at sky and you see red clouds.. }
{132}{}{You are archer.. but Gnome so you cant use longbows! }
{133}{}{Crossbow make more damage but is slow.. }
{134}{}{So make real crossbow and you will see! }
{135}{}{Its necklace made from metheorite its blue and shining.. }
{136}{}{Hah! You forgot to take off hat and she kick you balls! }
{137}{}{No you cant do that again! }
{138}{}{Wait! Let me count! Its 3k6! }
{139}{}{Nobody known that.. because its ancient. }
{140}{}{No you cant read it all! You skill is on second level!  }
