{10}{}{Some loser. }
{20}{}{He is total zero..}
{100}{}{Urgh.. yeah.. its that or.. nothing..}
{200}{}{What you do in my house?}
{250}{}{You horse? Fuck off! Its MY!}
{300}{}{Har du öl?}
{350}{}{Beer? Hahahah.. I have POWERFULL! drugs..}
{400}{}{What is your name?}
{450}{}{My name is Bond.. James Bond.. remember that.. Yeah! am tell him! Am best.. Am best in the universe.. Man! I could crush you by my one finger! And am so smart.. yeah! Am BEST!  }
{910}{}{SLUT}
{920}{}{TILLBAKA}
