{10}{}{Klamath Nyheter.}
{20}{}{News? They all are old stuff..}
{100}{}{=== K L A M A T H === N E W S === }
{200}{}{[Någon bild]}
{250}{}{Det är någon foto och skrifter: Den här mannen ät min katt!}
{300}{}{[Efterlyst!]}
{350}{}{Its some note: "I want Beer! Am so thirsty that i will crazy! Please give me someone just one drink!" uh.. i think i seen it before.. its MY note? }
{400}{}{[HETA GREJER TILL DIG!]}
{450}{}{Det är få foton av halvnakna kvinnar med stora bildtexter: "Badhus" Det finns också snuskig anteckning gjord i bråttom som troligen sattes in här av någon annan: "Fan! jag förlorade alla mina pengar där, men det var värt! Och nu jag ska prova något bättre.. kraftfula droger!"}
{910}{}{SLUT}
{920}{}{TILLBAKA }
