{10}{}{Soldat.}
{20}{}{He wear extremly dirty armor..}
{100}{}{[He look at you trough shade glasses and say something with cigarette in mouth] Hey folk, come here.. i have business for you.}
{200}{}{Me? What you want?}
{250}{}{I lost somewhere my dog tags, am not sure where because i was drunken. They could be in bathhouse because i dont remember any other place where i could lost them, check this place.. i will give you something for you trouble..}
{300}{}{Yes they was in Bathhouse.}
{350}{}{Tack! Ta denna tändare jag hittade dem många på slagfält..}
{400}{}{Sierraarmé, det var massaker!}
{401}{}{Och minns du Hangar18 i Navarro?}
{402}{}{Ja en sådan fantastisk strid!}
{403}{}{Gamla tider.. låt oss dricka för det!}
{404}{}{Am not sure they was aliens.. but who known!}
{910}{}{SLUT}
{920}{}{TILLBAKA }
