{10}{}{Punk.}
{20}{}{Pretty woman in black leather and green short hairs..}
{100}{}{[She say quickly] I have "Hero Jets" only 20$}
{200}{}{How it works?}
{250}{}{This mixture will help you to feel like hero. So what? Are you interested to buy it or not!? Make your decision faster i have many customers! Am inventioner and producer. Just 20$ come on!}
{300}{}{Uh.. ok let me try your Jet, here is money.}
{350}{}{Thanx. Take only one breath each day, its very strong!}
{400}{}{Nästa, tack!}
{401}{}{Hjälte Jet!}
{402}{}{Endast 20$}
{403}{}{Fuck off with these rocks!}
{404}{}{NÄSTA!}
{910}{}{SLUT}
{920}{}{TILLBAKA}
