{10}{}{Medborgare.}
{20}{}{Just some dirty folk which you seen many around..}
{100}{}{Helo.. [He look around to be sure that nobody hear him and say] ..are you interested to earn some cash?}
{200}{}{Sure, tell me about your problem.}
{250}{}{Am trying to fix my car, but damn i spend on this vehicle few months and its still not work! Its just impossible to fix it using only junk and rusty parts which can be found on streets. I want you to steal some parts from Smith. He is owner of junkyard over there! [he point finger in random direction] Bring me anything which look like engine.}
{300}{}{I found something in his workshop! He was so busy that dont seen when i take it. Easy job, now where is my money?}
{350}{}{What? I should do it myself.. uh ok here is your cash. Bye!}
{400}{}{I will drive highwaymen someday!}
{401}{}{Every chicks will jump into my car!}
{402}{}{::VÄS!::}
{403}{}{::SKRUV!::}
{404}{}{::BANG!::}
{910}{}{SLUT}
{920}{}{TILLBAKA}
