{10}{}{Auserwähltes Wesen.}
{20}{}{Sie, alle Stammesangehörigen, sehen gleich aus ..}
{100}{}{Verdammt! Ich werde dort sterben...ich weiß es!}
{200}{}{Hallo Mann! Was ist los?}
{250}{}{Hexe mich auserwählt für Test im Tempel. Ich Angst zu betreten, weil niemand zurückkommen...kannst du hören Schrei aus Dunkelheit? Jeder gestorben dort. Sie muss sehr dumm sein, zu töten unsere Brüder und Schwestern in dummen Test!}
{300}{}{Habt ihr Bier?}
{350}{}{[Er sieht in Dunkelheit des Tempels und ignoriert deine Frage]}
{400}{}{Isch bin so durstisch! Vielleischt finde isch was in diesen...hick, Tämpel?}
{450}{}{Oh ja... Tempel hat viel Schätze aus vergangener Welt. Jetzt mich in Ruhe lassen! Muss kleinen ersten Schritt in Dunkelheit machen...aber ich Angst haben mein Bein zu bewegen.}
{910}{}{Ende}
{920}{}{Zurück}
