{10}{}{Dorfbewohner.}
{20}{}{Sie alle sehen gleich aus...}
{100}{}{Hallo Fremder...hast komische Stimme von Quelle gehört?}
{200}{}{Ja, es klang wie ein Schrei von einem Hund.}
{250}{}{Nein, muss was anderes sein. Muss alter Geist der Erde sein...und braucht Opfer aus Erdelement gemacht. Geh Getreidefeld und bringen mir ein paar große Steine...}
{300}{}{Schau! Ich habe einen gefunden.}
{350}{}{Opfer hier für Göttter von Erde! [Der Dorfbewohner wirft diesen Stein in den Brunnen und nach einem kurzem Schrei herrscht Totenstille.] Freund danke, jetzt Geist sein glücklich und nicht mehr schreien. Hier nehmen Belohnung, wunderschön Blume wachsen neben Quelle.}
{400}{}{Wir jetzt geseegnet sein von Erde!}
{401}{}{So viele Fliegen um magischer Quelle!}
{402}{}{Gesegnete Stille.}
{403}{}{Igit, was ist das für ein Gestank?}
{404}{}{Danke, mein Freund!}
{910}{}{Ende}
{920}{}{Zurück}
