{10}{}{Dorfbewohner.}
{20}{}{Sie alle sehen gleich aus...}
{100}{}{Verloren meinen Hund. Äh...Angst haben, jemand ihn essen. Außenweltler, du rausfinden können, wo mein dreckiges Tier gegangen ist? Seine name "Klint" war.}
{200}{}{Ich mag es nicht, Rätsel zu lösen.}
{250}{}{Ah ja, du nicht klug sehen aus. Schlimm nicht, werden hier bis kommen er zurück. Er wahrscheinlich rennen um Dorf, jagen Ratten.}
{300}{}{Habt ihr Bier?}
{350}{}{[Er sieht umher, um den Hund zu suchen und ignoriert deine Frage]}
{400}{}{Er zähl mir ewtas von diesem Dorf.}
{450}{}{Wir in Frieden weit entfernt von Zivilisation wohnen. Ältesten sagen, Technik nur bringen Schmerz und Zerstörung, so wir glauben nur in traditionelle Magie von Schamanen. Aber eines Tages kommen Händler Vic mit sein tollen Zeug. Heilige Geister uns dann verlassen und viel Leute werden krank.}
{910}{}{Ende}
{920}{}{Zurück}
