{10}{}{Dorfbewohner.}
{20}{}{Sie alle sehen gleich aus...}
{100}{}{Nicht ich glauben können! Du geschafft haben durch Tempel, niemand schaffen zuvor. Du seinen unser Champion jetzt! Geh und sprechen mit Ältesten, sie dir sagen müssen wichtige Dinge.}
{200}{}{Oh...bist du die Wache, die ich in der Nähe des Tempels gesehen habe? Entschuldige, ihr Stammesangehörige seht für mich alle gleich aus.}
{250}{}{Ja, ich bin wache und großer Krieger "Klint". Ich übrigens hassen Bastard der nennen seinen Hund nach meinem berühmten Namen nennt. Ich hoffen, dass ich gestern es gelöst habe und ich fühlen besser jetzt.}
{300}{}{Und was ist mit dem Kerl passiert, der Angst hatte den Tempel zu betreten?}
{350}{}{Er entkommen ist durch Wald außerhalb des Dorfes, selbe durch den du gekommen hier. Hoffen er nicht kommen wieder, ich nämlich mögen Verlierer!}
{400}{}{Ja, ICH bin ein Held! Jetzt gib mir endlich BIER!}
{450}{}{Entschuldigen, nicht wissen ich, was sein das...Reden mit Ältesten, sie wissen viel über heilige Artefakte. Und sie handeln mit Händler Vic, er uns bringen viel seltsames Zeug von der Außenwelt.}
{910}{}{Ende}
{920}{}{Zurück}
