{10}{}{Dorfbewohner.}
{20}{}{Sie alle sehen gleich aus...}
{100}{}{Ich bin so müde...Hey schmutziger Mann! Kannst du mir helfen?}
{200}{}{Oh, nicht sicher sein...was brauchen?}
{250}{}{Schamane möchte liefern mehr Scheiße, aber meine Schaufel sein zu schwer. Bringen mir neue, saubere. Sie sollte liegen nahe der Zelte dadrüben! [Sie zeigt mit dem Finger in eine zufällige Richtung und sitzt auf dem Boden und versucht Schuhe zu putzen]}
{300}{}{Ich habe die saubere Schaufel gefunden!}
{350}{}{Tanke schön Mann...ich werden die Arbeit später beenden, weil bin zu müde. Nehmen glänzende Dinge, die Vic geben mir für einen Kuss. Ich hören, man viele Dinge kann kaufen für Sache genannt..."Geld".}
{400}{}{Ich bin so müde...}
{401}{}{Ich rieche nach Brahmin...}
{402}{}{Verdammt, meine Schuhe sind schwer...}
{403}{}{Ein weiterer wundervoller Tag ...}
{404}{}{Lass mich in Ruhe, ich bin beschäftig...}
{910}{}{Ende}
{920}{}{Zurück}
