{10}{}{Schamane.}
{20}{}{Er sieht wirklich verrückt aus...}
{100}{}{Hahahah...schaut euch die Formen und Farben an!!}
{200}{}{Hä...von was sprichst du?}
{250}{}{Hahahah...entschuldige, ich vergessen, du nicht siehst, was ich sehen kann! Ich erfunden wunderbare Mixtur. Herstellen aus Brahminscheiß und Broc Blume. Da nicht haben genug Blumen, bringen mir eine und ich helfen zu sehen dir, versteckte Seite von unglaublichen Welt.}
{300}{}{Ich habe die Blume, kannst du jetzt die Mixtur für mich herstellen?}
{350}{}{Oh, jaaa! [Er nimmt die Blume von dir und ein Stück Kacke vom Fass, eine Halbestunde später gibt er dir die wunderbare Mischung.]}
{400}{}{Helft mir! Ein Schlangenvogel greift meinen Schuh an.}
{401}{}{Warum flüchtet dieser Fels vor mir?!}
{402}{}{Wow, ich hab ne dritte Hand!!}
{403}{}{Was ist das?! Ich kann es nicht fangen!!!}
{404}{}{Feuer! Mein Haus brennt!!}
{910}{}{Ende}
{920}{}{Zurück}
