{100}{}{Du hast eine wunderbare Vision, aber du fühlst dich krank.}
{101}{}{Ich bin Herr Fliege! Und ich bin schnell wie der Wind!}
{102}{}{Wo sind meine Schuhe? Polizei! Jemand hat meine Schuhe geklaut!!}
{103}{}{Stark...mein Kpf ist so GROß!}
{104}{}{Ich habe Gold gefunden!...nee, ist nur ein Stein.}
{105}{}{Schaut euch den Regenbogen an!!}
{106}{}{Ich kann mein Bein nicht bewegen! Argh!! Helft mir!}
{107}{}{Was ist den mit meinen Fingern? Ich habe sie zu viel...}
{108}{}{Ich bin unsichtbar!}
{109}{}{Ich bin schneller als eine Kugel! Wow, ich beweg mich so schnell!}
{110}{}{Wo ist mein Becher?! Oh...ich habe ihn in der Hand...}
{111}{}{Was ist das am Himmerl?...ist das ein UFO!?}
{112}{}{Ah! Schlangenratten haben meine Schuhe gefressen!}
{113}{}{Ich bin so groß! Ich könnte dich mit meinem Finger zerquetschen!}
{114}{}{Warum ist meine Hose plötzlich so nass?!}
{115}{}{Hey! Du! Vogelkopf! Komm schon!}
{116}{}{Ich glaube ich kann über das Haus springen...}
{117}{}{Ich bin ein Hase...Ich will auf den Baum klettern!}
{118}{}{Maus? Ich habe eine Maus in der Tasche!}
{119}{}{Warum beobachten diese Felsen mich?!}
{120}{}{Ich habe meinen Hut verloren!! Oh, hatte ich überhaupt einen Hut?}
{121}{}{Wo sind meine Haare? Uhi...Ich habe sie in der Tasche!}
{122}{}{Verdammt! Mein Becher ist leer!}
{123}{}{Alles ist so langsam...hey du! Komm schon!}
{124}{}{Yeah, ich mag diese Musik!!!}
{125}{}{Was willst du von mir?! Verpiss dich du verdammte Ratte!}
{126}{}{Was wollen diese Fliegen von mir?!}
{127}{}{Was sagt dieser Hund?!}
{128}{}{Wow, meine Hand ist so laaaaannnng!!}
{129}{}{Warum bin so grün? Oh nein, ich bin ein Supermutant!!}
{130}{}{Polizei! Hasen haben meine Finger gestohlen!!}
