{10}{}{Soldier. }
{20}{}{He wear extremly dirty armor..}
{100}{}{[He look at you trough shade glasses and say something with cigarette in mouth] Hey folk, come here.. i have business for you.}
{200}{}{Me? What you want?}
{250}{}{I lost somewhere my dog tags, am not sure where because i was drunken. They could be in bathhouse because i dont remember any other place where i could lost them, check this place.. i will give you something for you trouble..}
{300}{}{Yes they was in Bathhouse.}
{350}{}{Thanx! Take this lighter i found them many on battlefield..}
{400}{}{Sierra Army, now that was massacre!}
{401}{}{And do you remember Hangar18 in Navarro?}
{402}{}{Yeah such a great battle!}
{403}{}{Old times.. lets drink for that!}
{404}{}{Am not sure they was aliens.. but who known!}
{910}{}{Ende}
{920}{}{Zurück}
