{10}{}{Citizen. }
{20}{}{Sie alle sehen gleich aus...}
{100}{}{[He sit near table and writing something in silence]}
{200}{}{Habt ihr Bier?}
{250}{}{No.. [He seem to be very busy on book]}
{300}{}{Was du machen?}
{350}{}{Am writing diary.. [you look at page and read few fragments] "..today i found amazing items, not like trash yesterday.. i found very white bone, almost new!.. i found rope, almost one meter long!.. i found three nails, well they was little rusty and have weird shape.. thats all i found! Such a great day! Tomorrow i will search again.. my collection is best in the world!}
{400}{}{Do you seen GECK?}
{450}{}{Yes ofcourse! [he shown you some junk, everything he have is junk] As you see i have everything, am best trader in the universe! Vic sell me many items, but also i found lot of treasures outside town. Some day i will open shop called "1001 items" this will be great day am tell you! And i will sell THIS book about my bartering career. }
{910}{}{Ende}
{920}{}{Zurück}
