{10}{}{VIC. }
{20}{}{He smiling in irony..}
{100}{}{WELCOME! brother i have MANY amazing items, which waiting for YOU! Just share with me your DREAMS and i will give you EVERYTHING you need! Look into my boxes and select your FAVOURITE item!}
{200}{}{[you look into dirty boxes filled with junk] I dont see GECK..}
{250}{}{GECK? Yes.. LEGENDARY geck! Well i dont have it YET but i COULD have IT. Just bring me something made from GOLD. I have MANY connections and EVERYTHING you need am ABLE to find!}
{300}{}{I have golden watch.}
{350}{}{WOW! Your GECK will be ready for one minute! [He run into next room and after minute returned with.. something which look like GECK!] HERE it is! UNLESS you NEED instruction to use it properly, i dont have it YET! Come back Next month, maybe i will find it. Now good BYE!}
{400}{}{I DONT have this instruction YET}
{401}{}{No.. its WORK! You just dont known HOW use it!}
{402}{}{Come back LATER.. maybe next month.}
{403}{}{Sorry am BUSY right now!}
{404}{}{My shop is TEMPORARY closed!}
{910}{}{Ende}
{920}{}{Zurück}
