{10}{}{Smith. }
{20}{}{His skin and clothes are really dirty, the same like tools which he hold in hands..}
{100}{}{[He look very busy on some dirty metalic stuff, probably part of engine] Uh.. hello. Do you need to repair something?}
{200}{}{Am wonder about these strange obiects in junkyard.}
{250}{}{I found them many crashed on desert near Navarro. One from my friends say they are alien ships. But am not sure about that theory, because there is no space for pilot inside. Seem like they are spying robots. Am not sure why they crashed, maybe bacause wrong program in main computer. As you see am trying to repair one, but it seem to be really dificulty [When you look at this machine it seem to be really hard to understand how it work and require skills science and repair near 300%] }
{300}{}{Can you borrow me your car? }
{350}{}{Forget about that i spend half year to repair it. Find some brahmin and drive it like others do. And DONT touch my car or i will change your face shape! [He point you big hammer on table] }
{400}{}{Habt ihr Bier?}
{450}{}{[He seem to be too busy for such question]}
{910}{}{Ende}
{920}{}{Zurück}
