{10}{}{sir Marcus. }
{20}{}{Leader of Bloor Reaven squad.}
{100}{}{If you wish to join Brotherhood of Steel army you must pass trough few basic tests in next room. Our weapons are very dangerous and we fear fools who panic during battle. Go to next room and talk with our psychiatry.}
{200}{}{Uh.. and any other chances to join BoS?}
{250}{}{Yes it is other possibility. We search plans of Scout Disc known as UFO. Our best scients and engineers dont known how they work. We have many reports about secret base near Navarro where they fly, so try your luck there. }
{300}{}{i found}
{350}{}{thanx}
{400}{}{r1}
{401}{}{r2}
{402}{}{r3}
{403}{}{r4}
{404}{}{r5}
{910}{}{Ende}
{920}{}{Zurück}
