{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Eu não acredito! Você passou pelo templo, ninguém nunca conseguiu isso antes! Você agora é nossa campeã!. Vá falar com a anciã, ela tem algo muito importante para dizer para você.}
{200}{}{Uh... Você é este guarda o qual eu vi perto da entrada do templo? Lamento, vocês todos tribais parecem os mesmos pra mim.}
{250}{}{Sim eu sou guarda e um grande guerreiro "Klint" por falar nisso eu odeio o idiota que chama seu cachorro pelo meu nome de fama. Eu consertei esse problema ontem e eu me sinto melhor agora.}
{300}{}{E o que acontece com o cara que teme entrar?}
{350}{}{Ele escapou através da floresta no lado de fora da vila, do mesmo jeito pelo qual você chegou aqui. Eu espero que ele nunca retorne porque eu não gosto de perdedores!}
{400}{}{Sim sou herói! Agora me dê cerveja!}
{450}{}{Desculpa mas eu não sei o que é... Fale com a Anciã, ela sabe muitas coisas sobre os grandes artefatos. E ela negocia com Vis o comerciante, que traz muitas coisas estranhas do mundo lá fora.}
{910}{}{FIM }
{920}{}{VOLTAR }
