{10}{}{Aldeão. }
{20}{}{Eles todos parecem os mesmos...}
{100}{}{Estou tão cansado... Ei homem sujo! Você pode me ajudar?}
{200}{}{Uh, não tenho certeza... O que você precisa?}
{250}{}{Shaman want to deliver him more shit, but my shovel is so heavy. Bring me new, clean one. It shold lay somewhere near tents over there! [She point finger in random direction and sit on ground trying to clean shoes]}
{300}{}{Eu achei pá limpa!}
{350}{}{Thanx man.. i will finish my job later, because am too tired. Take this shining items which Vic gived me for one kiss. I heard that many things can be buy for such thing called.. "money".}
{400}{}{Estou tão cansado...}
{401}{}{Eu cheiro mal igual brahmin...}
{402}{}{Maldição! Eu tenho sapatos pesados...}
{403}{}{Outro dia maravilhoso...}
{404}{}{Me deixe em paz, estou ocupado...}
{910}{}{FIM }
{920}{}{VOLTAR }
