{10}{}{Xamã.}
{20}{}{Ele parece realmente louco...}
{100}{}{Hahahah... Olha essas formas formas e cores!!}
{200}{}{Uh... Do quê você está falando?}
{250}{}{Hahahah.. sorry i forgot that you dont see what i see! I invented wonderfull mixture. Its made from brahmin shit and broc flower. Unless i dont have too much flowers. Bring me one and i will help you to see hidden side of amazing world!}
{300}{}{Eu tenho a flor, você poderia me fazer a mistura?}
{350}{}{Aí sim porra! [Ele pega a flor da sua mão e um pedaço de merda do barril.Depois de meia ele te entrega a mistura incrível].}
{400}{}{Me ajuda! Passáro cobra atacando meu sapato!}
{401}{}{Porquê essas pedras escapam de mim?}
{402}{}{Uau eu tenho uma terceira mão!!}
{403}{}{O quê é isto? Eu não consigo pegar!!}
{404}{}{Fogo! Minha casa tá pegando fogo bicho!!}
{910}{}{FIM }
{920}{}{VOLTAR }
