{10}{}{Algum velhote.}
{20}{}{Ele parece ser muito sábio...}
{100}{}{Olá estranho... você é o amigo do Vic?}
{200}{}{Eu vi aquele homem algumas vezes em Klamath. Uma vez ele me vendeu uma cerveja que tinha gosto de mijo.}
{250}{}{Então você não gosta dele? Essa vila é separada em dois grupos, "Esses" que gostam de tradições e "Aqueles" que gostam de itens técnicos, Eu sou dos "Esses", que seguem as pregações dos nossos anciãos que dizem que técnica traz apenas dor e destruição...}
{300}{}{Você é a anciã?}
{350}{}{Yes, but we have many elders here: traditionalists and these who deal with outsiders like Vic. Probably you search witch who lately need champion for big quest. She is in tent to the south from here.}
{400}{}{Whats going around lately?}
{450}{}{Witch need brave man who will search some technical stuff. Its called GECK. Vic trader tell about it many weird stories. I think our situation will change into worst when someone find it. Whole sick problems which we got here is only because shaman inventions. Its dont need to fall into panic and make risky decisions.. }
{910}{}{FIM }
{920}{}{VOLTAR }
